x-cli-zendesk: &cli-zendesk
  image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:1.7.3}
  environment:
    - COMMUNITY_ID=${COMMUNITY_ID:-1111}
    - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
    - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
    - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-cli-zendesk}
    - NODE_ENV=${NODE_ENV:-production}
    - WIDGET_IDS=${WIDGET_IDS:-a1111}
    - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
    - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
    - ZENDESK_API_USER=${ZENDESK_API_USER_WITH_TOKEN:-email@host}
    - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS}
    - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
    - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
    - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    - DEBUG=${DEBUG:-cli-zendesk*}
    - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-false}
    - HASURA_API_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
    - X_HASURA_ADMIN_SECRET=${X_HASURA_ADMIN_SECRET:-segredo123}

services:
  #banco para staging    
  mautic-nossasdb:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysecret}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    labels:
      - traefik.enable=true
      - traefik.http.services.mautic-nossasdb.loadbalancer.server.port=3306
      - traefik.http.routers.mautic-nossasdb.tls=true
      - traefik.http.routers.mautic-nossasdb.tls.certresolver=myresolver

  mautic-nossas:
    image: mautic/mautic:v4
    environment:
      - MAUTIC_DB_HOST=${MAUTIC_DB_HOST:-mautic-nossasdb}
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME:-mautic}
      - MAUTIC_DB_PASSWORD=${MAUTIC_DB_PASSWORD:-mysecret}
      - MAUTIC_DB_USER=${MAUTIC_DB_USER:-root}
      - MAUTIC_RUN_CRON_JOBS=${MAUTIC_RUN_CRON_JOBS:-true}
      - MYSQL_PORT_3306_TCP=${MYSQL_PORT_3306_TCP:-3306}
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0\\/0"]
    depends_on:
      - mautic-nossasdb
    volumes:
    - mautic-nossas_data:/var/www/html
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      - traefik.http.services.mautic-nossas.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.mautic-nossas.rule=Host(`${MAUTIC_URL}`)
      - traefik.http.routers.mautic-nossas.tls=true
      - traefik.http.routers.mautic-nossas.tls.certresolver=myresolver

  cli-zendesk-ticket:
    <<: *cli-zendesk
    command:
    - pnpm
    - --filter
    - bonde-cli-zendesk
    - run
    - start:ticket
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  cli-zendesk-user:
    <<: *cli-zendesk
    command:
    - pnpm
    - --filter
    - bonde-cli-zendesk
    - run
    - start:user
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  listener-solidarity:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:1.7.3}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1111}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-listeners-solidarity}
      - GRAPHQL_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - HASURA_SECRET=${X_HASURA_ADMIN_SECRET:-a11111}
      - LAWYER_WIDGET_IDS=${LAWYER_WIDGET_IDS:-a1111}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.bonde.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-a1111}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - THERAPIST_WIDGET_IDS=${THERAPIST_WIDGET_IDS:-a1111}
      - WS_GRAPHQL_URL=${WS_GRAPHQL_URL:-ws://api-graphql.bonde.devel/v1/graphql}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER:-email@host}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS_EN}
      - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    command:
    - pnpm
    - --filter
    - listener-solidarity
    - run
    - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  listener-match:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:1.7.3}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1111}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-listeners-match}
      - GRAPHQL_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - HASURA_SECRET=${X_HASURA_ADMIN_SECRET:-a11111}
      - NODE_ENV=${NODE_ENV:-production}
      - WS_GRAPHQL_URL=${WS_GRAPHQL_URL:-ws://api-graphql.bonde.devel/v1/graphql}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER:-email@host}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS_EN}
      - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    command:
    - pnpm
    - --filter
    - listener-match
    - run
    - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  solidarity-count:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:1.7.3}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1}
      - DEBUG=${DEBUG:-events-solidarity-count*}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-aaaa1}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://aaaa1.apm.us-east-1.aws.found.io}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-aaaa1}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-aaaa1}
      - HASURA_API_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.nossas.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-aaaa1}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=80
      - X_HASURA_ADMIN_SECRET=${X_HASURA_ADMIN_SECRET:-aaaa1}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-aaaa1}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaaa1.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER_WITH_TOKEN:-email@host/token}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS_SOLIDARITY_COUNT}
      - WIDGET_IDS=${WIDGET_IDS_SOLIDARITY_COUNT:-aaaa1}
    command:
      - pnpm
      - --filter
      - bonde-webhooks-solidarity-count
      - run
      - start
    labels:
      - traefik.http.services.events-solidarity-count.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.events-solidarity-count.tls=true
      - traefik.http.routers.events-solidarity-count.tls.certresolver=myresolver
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  mautic-zendesk:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:1.7.3}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1}
      - DEBUG=${DEBUG:-events-mautic-zendesk*}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-aaaa1}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://aaaa1.apm.us-east-1.aws.found.io}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-aaaa1}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-aaaa1}
      - HASURA_API_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.nossas.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-aaaa1}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=80
      - X_HASURA_ADMIN_SECRET=${X_HASURA_ADMIN_SECRET:-aaaa1}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-aaaa1}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaaa1.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER_WITH_TOKEN:-email@host/token}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS}
      - WIDGET_IDS=${WIDGET_IDS_MAUTIC_ZENDESK:-aaaa1}
    command:
      - pnpm
      - --filter
      - bonde-webhooks-mautic-zendesk
      - run
      - start
    labels:
      - traefik.http.services.events-mautic-zendesk.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.events-mautic-zendesk.tls=true
      - traefik.http.routers.events-mautic-zendesk.tls.certresolver=myresolver
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

volumes:
  mautic-nossas_data:
    driver: local
  mysql_data:
    driver: local 

networks:
  default:
    external:
      name: bonde