pipeline:
  elasticsearch:
    image: plugins/docker
    repo: nossas/elasticsearch
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile:  elasticsearch/Dockerfile
    context:  elasticsearch/
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  logstash:
    image: plugins/docker
    repo: nossas/logstash
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile:  logstash/Dockerfile
    context:  logstash/
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  kibana:
    image: plugins/docker
    repo: nossas/kibana
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile:  kibana/Dockerfile
    context:  kibana/
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  logspout:
    image: plugins/docker
    repo: nossas/logspout
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile:  extensions/logspout/Dockerfile
    context:  extensions/logspout/
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  # infrastructure:
  #   image: rancher/os:v1.3.0
  #   commands:
  #     - echo 'docker run --rm radial/busyboxplus:curl curl $@' > /usr/bin/curl && chmod +x /usr/bin/curl
  #     - curl -L https://github.com/docker/compose/releases/download/1.21.0-rc1/docker-compose-`uname -s`-`uname -m` >> /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose
  #     - curl -L https://github.com/concourse/concourse/releases/download/v3.10.0/fly_linux_amd64 >> /usr/bin/fly && chmod +x /usr/bin/fly

