version: '2'
services:

  public:
    image: nossas/bonde-public-ts:0.3.4
    # build: ../server/webpage
    environment:
      GOOGLE_FONTS_API_KEY: A
      NODE_ENV: production
      PORT: '3000'
      REACT_APP_API_GRAPHQL_SECRET: segredo123
      REACT_APP_DOMAIN_API_ACTIVISTS: http://api-graphql:8080/v1/graphql
      REACT_APP_DOMAIN_API_GRAPHQL: http://api-graphql:8080/v1/graphql
      REACT_APP_DOMAIN_API_REST: http://api-rest:3000
      REACT_APP_DOMAIN_PUBLIC: bonde.devel
      REACT_APP_PAGARME_KEY: ak_test
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    command:
    - yarn
    - start
    labels:
      - traefik.enable=true
      - traefik.http.routers.public.rule=hostregexp(`{host:.+}`)
      - traefik.http.services.public.loadbalancer.server.port=5001
