version: '2'
networks:
  bonde:
volumes:
  redis_data:
    driver: local
  es_data:
    driver: local
  fn_data:
    driver: local
services:
  redis:
    image: redis:3
    volumes:
    - redis_data:/var/lib/redis
    ports:
    - 6379:6379/tcp
    command:
    - redis-server
    - --appendonly
    - 'yes'
  dispatcher-notification:
    image: nossas/fn-dispatcher:develop
    environment:
      API_KEY: jwt_token_hs512
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgpool:5432/bonde
      DB_CHANNEL: notifications_channel
      DISPATCHER_FN_APP: notification-service
      DISPATCHER_FN_ROUTE: /notification-service
      FN_API_URL: fnserver:8080
      FN_PORT: '8080'
      REDIS_URL: redis://redis:6379
      WORKERS: '5'
    external_links:
    - pgpool
    links:
    - fnserver
    - redis
    depends_on:
    - redis
    networks:
      - bonde
  fnserver:
    image: fnproject/fnserver
    environment:
      FN_DB_URL: postgres://monkey_user:monkey_pass@pgpool:5432/fnserver?sslmode=disable
      FN_LOGSTORE_URL: s3://admin:password@s3:9000/us-east-1/fnlogs
      FN_MQ_URL: redis://redis:6379/
    external_links:
    - pgpool
    - s3
    links:
    - redis
    volumes:
    - fn_data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ports:
    - 54513:8080/tcp
    labels:
      traefik.frontend.rule: Host:fn.bonde.devel
      traefik.port: '8080'
      traefik.enable: 'true'
    networks:
      bonde:
        aliases:
          - fnserver
  fnserver-ui:
    image: fnproject/ui
    environment:
      FN_API_URL: http://fnserver:8080
    links:
    - fnserver
    ports:
    - 4000:4000/tcp
    networks:
      - bonde
    labels:
      traefik.frontend.rule: Host:fn-ui.bonde.devel
      traefik.port: '4000'
      traefik.enable: 'true'
  dispatcher-domain:
    image: nossas/fn-dispatcher:develop
    environment:
      API_KEY: jwt_token_hs512
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgpool:5432/bonde
      DB_CHANNEL: dns_channel
      DISPATCHER_FN_APP: domain-service
      DISPATCHER_FN_ROUTE: /domain-service
      FN_API_URL: fnserver:8080
      FN_PORT: '8080'
      REDIS_URL: redis://redis:6379
      WORKERS: '5'
    external_links:
    - pgpool
    links:
    - redis
    - fnserver
    depends_on:
    - redis
    networks:
      - bonde