version: '2'
networks:
  bonde:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.0.0.0/8

services:

  migrations:
    image: nossas/bonde-server:develop
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_BUCKET: bonde
      AWS_ID: admin
      AWS_ROUTE53_REGION: sa-east-1
      AWS_ROUTE53_SYNC: force
      AWS_ROUTE_IP: 127.0.0.1
      AWS_SECRET: password
      AWS_SECRET_ACCESS_KEY: password
      CLIENT_APP_NAME: hub-client
      CLIENT_HOST: bonde.devel
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgpool:5432/bonde
      JWT_SECRET: segredo123
      JWT_TYPE: postgraphql.jwt_token
      MAILCHIMP_API_KEY: 1111111-us6
      MAILCHIMP_GROUP_ID: '111'
      MAILCHIMP_LIST_ID: 111111ac
      NEW_RELIC_LICENSE_KEY: 1111111111
      NEW_RELIC_LOG: stdout
      NO_VHOST: '0'
      ORG_RECIPIENT_ID: xxxxxxxx
      PAGARME_API_KEY: xxxxxxxx
      PORT: '3000'
      RAILS_ENV: staging
      RAILS_SERVE_STATIC_FILES: enabled
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: xxxxxxxxx
      SMTP_PASSWORD: xxxxx
      SMTP_USERNAME: xxxxx
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SENTRY_DSN: https://xxxxxx:xxxxxx@sentry.io/121379
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    external_links:
    - pgpool
    - redis
    command:
    - bundle
    - exec
    - rake
    - db:migrate
    labels:
      io.rancher.container.start_once: 'true'
    networks:
      - bonde

  seeds:
    extends:
      service: migrations
    command: ["bundle", "exec", "rake", "db:seed"]

  mailchimp:
    extends:
      service: migrations
    command: ["bundle", "exec", "sidekiq", "-c", "5", "-q", "mailchimp_synchro"]

  mailers:
    extends:
      service: migrations
    command: ["bundle", "exec", "sidekiq", "-q", "default", "-q", "mailers", "-c", "5"]

  templates-email:
    extends:
      service: migrations
    command: ["bundle", "exec", "rake", "notifications:all"]

  bot-worker:
    image: nossas/bonde-bot:develop
    environment:
      API_URL: http://api-v1:3000
      APP_DOMAIN: http://beta.bonde.devel
      GRAPHQL_URL: http://api-v2:3002/graphql
      JWT_TOKEN: xxxxxxxxx
      PORT: '5000'
      REDIS_URL: redis://redis:6379
      SPEECH_VERSION: v1
      WIT_SERVER_ACCESS_TOKEN: xxxxxxxxx
    external_links:
    - redis
    - api-v2
    - api-v1
    command:
    - npm
    - run
    - start:worker
    labels:
      io.rancher.container.start_once: 'true'
    networks:
      - bonde
