version: '2'

# /etc/hosts 127.0.0.1 api-graphql.bonde.devel traefik.bonde.devel bonde.devel

volumes:
  redis_data:
    driver: local
  s3_data:
    driver: local
  pgmaster_data:
    driver: local

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    # - --configfile=/traefik.toml
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./traefik.toml:/traefik.toml"
    environment:
      AWS_ACCESS_KEY_ID: xxxxxxx
      AWS_SECRET_ACCESS_KEY: xxxxxx
      AWS_REGION: us-east-1
    labels:
      - traefik.enable=true
      - "traefik.http.routers.traefik.rule=Host(`traefik.bonde.devel`)"
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  api-graphql:
    image: hasura/graphql-engine:v2.2.0.cli-migrations-v3
    restart: always
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: 'startup, query-log, http-log, webhook-log, websocket-log'
      HASURA_GRAPHQL_LOG_LEVEL: DEBUG
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      WEBHOOK_ACTIVISTS_PRESSURE_URL: ${WEBHOOK_ACTIVISTS_PRESSURE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      SCHEMA_API_ACTIVISTS_URL: ${SCHEMA_API_ACTIVISTS_URL}
      SCHEMA_API_AUTH_URL: ${SCHEMA_API_AUTH_URL}
      SCHEMA_API_DOMAINS_URL: ${SCHEMA_API_DOMAINS_URL}
      SCHEMA_API_NOTIFICATIONS_URL: ${SCHEMA_API_NOTIFICATIONS_URL}
      SCHEMA_API_PAYMENTS_URL: ${SCHEMA_API_PAYMENTS_URL}
      SCHEMA_API_REDES_URL: ${SCHEMA_API_REDES_URL}
      WEBHOOK_INVITATIONS_URL: ${WEBHOOK_INVITATIONS_URL}
      SCHEMA_API_V2_URL: ${SCHEMA_API_V2_URL}
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: "false"
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      PORT: 8080
    volumes:
       - ../apis/api-graphql/migrations/migrations:/hasura-migrations
       - ../apis/api-graphql/migrations/metadata:/hasura-metadata
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-graphql.rule=Host(`api-graphql.bonde.devel`)
      - traefik.http.services.api-graphql.loadbalancer.server.port=8080