version: '2'
services:

  chatbot:
    image: nossas/bonde-bot:develop
    # build:
    #   context: ./../bonde-bot
    environment:
      API_URL: http://api-v1:3000
      REDIS_URL: redis://redis:6379
      SPEECH_VERSION: v1
      WIT_SERVER_ACCESS_TOKEN: xxxxxxxxx
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
    external_links:
    - redis
    - api-graphql
    - api-v1

  notifications:
    build: ../bonde-microservices
    environment:
      DEBUG: webhook-mail*
      PORT: 8080
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USER: xxxxxxxx
      SMTP_PASS: xxxxxxxx
    command: node packages/webhook-mail/dist

    redes:
      # image: nossas/bonde-redes:develop
      environment:
      build: ../bonde-microservices
      environment:
        GRAPHQL_URL: http://api-graphql:8080/v1/graphql
        WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
        HASURA_SECRET: segredo123
      external_links:
      - api-graphql
      command: node packages/listener-redes/dist

    redes-individuals-geolocation:
      # image: nossas/bonde-redes:develop
      environment:
        build: ../bonde-microservices
      environment:
        GRAPHQL_URL: http://api-graphql:8080/v1/graphql
        WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
        HASURA_SECRET: segredo123
      external_links:
      - api-graphql
      command: node packages/listener-redes-geolocation/dist
