version: '2'
services:

  chatbot:
    image: nossas/bonde-bot:develop
    # build:
    #   context: ./../bonde-bot
    environment:
      API_URL: http://api-v1:3000
      REDIS_URL: redis://redis:6379
      SPEECH_VERSION: v1
      WIT_SERVER_ACCESS_TOKEN: xxxxxxxxx
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
    external_links:
    - redis
    - api-graphql
    - api-v1

  notifications:
    build:
      dockerfile: packages/webhook-mail/Dockerfile
      context: ../bonde-microservices
    environment:
      DEBUG: webhook-mail*
      PORT: 8080
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USER: xxxxxxxx
      SMTP_PASS: xxxxxxxx

  redes:
    # image: nossas/bonde-redes:develop
    environment:
    build:
      dockerfile: packages/listener-redes/Dockerfile
      context: ../bonde-microservices
    environment:
      PORT: 8081
      HASURA_API_URL: http://api-graphql:8080/v1/graphql
      X_HASURA_ADMIN_SECRET: segredo123
      DEBUG: webhooks-registry*
    external_links:
    - redis
    - api-v2
    - api-v1
