version: '2'
networks:
  bonde:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.0.0.0/8
services:
  donations:
    image: nossas/bonde-server:develop
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_BUCKET: bonde
      AWS_ID: admin
      AWS_ROUTE53_REGION: sa-east-1
      AWS_ROUTE53_SYNC: force
      AWS_ROUTE_IP: 127.0.0.1
      AWS_SECRET: password
      AWS_SECRET_ACCESS_KEY: password
      CLIENT_APP_NAME: hub-client
      CLIENT_HOST: bonde.develop
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgpool:5432/bonde
      JWT_SECRET: segredo123
      JWT_TYPE: postgraphql.jwt_token
      MAILCHIMP_API_KEY: 1111
      MAILCHIMP_GROUP_ID: '11'
      MAILCHIMP_LIST_ID: 111111ac
      NEW_RELIC_LICENSE_KEY: 111111111
      NEW_RELIC_LOG: stdout
      ORG_RECIPIENT_ID: xxxxxx
      PAGARME_API_KEY: xxxxxx
      PORT: '3000'
      RAILS_ENV: staging
      RAILS_SERVE_STATIC_FILES: enabled
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: xxxxxx
      SMTP_PASSWORD: xxxxxx
      SMTP_USERNAME: xxxxxx
      SENTRY_DSN: https://xxx:xxx@sentry.io/121379
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    external_links:
    - pgpool
    - redis
    command:
    - bundle
    - exec
    - rake
    - payments:sync_donations
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *
    networks:
      - bonde

  donations-recovery-from-metadata:
    extends:
      service: donations
    command: ["bundle", "exec", "rake", "payments:recovery_from_metadata"]

  donations-schedule-charges:
    extends:
      service: donations
    command: ["bundle", "exec", "rake", "subscriptions:schedule_charges"]

  donations-sync-gateway-transactions:
    extends:
      service: donations
    command: ["bundle", "exec", "rake", "payments:sync_gateway_transactions"]

  donations-sync-balance-operations:
    extends:
      service: donations
    command: ["bundle", "exec", "rake", "recipients:sync_balance_operations"]

  payments:
    image: nossas/bonde-payments:develop
    environment:
      AMOUNT: '100'
      API_HOST: bonde.devel
      CLIENT_APP_NAME: hub-client
      DATABASE_URL: postgres://postgres_user:postgres_password@pgpool:5432/bonde
      JWT_SECRET: segredo123
      JWT_TYPE: postgraphql.jwt_token
      NEW_RELIC_LICENSE_KEY: xxxxxxxxxx
      NEW_RELIC_LOG: stdout
      NO_VHOST: '0'
      ORG_RECIPIENT_ID: xxxxxxxx
      PAGARME_API_KEY: xxxxxxx
      PORT: '3000'
      REDIS_URL: redis://redis-local:6379
      RUBY_ENV: staging
      SECRET_KEY_BASE: xxxxxxxxx
      SENTRY_DSN: https://xxxxx:xxxxx@sentry.io/121379
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    stdin_open: true
    external_links:
    - pgpool
    - redis
    tty: true
    command:
    - ruby
    - -I
    - .
    - -r
    - app/main
    - -e
    - Main.new.sync_recipients 'available'
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *
    networks:
      - bonde

  payments-waiting-funds:
    extends:
      service: payments
    command:
    - ruby
    - -I
    - .
    - -r
    - app/main
    - -e
    - Main.new.sync_recipients 'waiting_funds'

  payments-transferred:
    extends:
      service: payments
    command:
    - ruby
    - -I
    - .
    - -r
    - app/main
    - -e
    - Main.new.sync_recipients 'transferred'
