version: '2'

volumes:
  redis_data:
    driver: local
  s3_data:
    driver: local
  pgmaster_data:
    driver: local

services:
  s3:
    extends:
      file: docker-compose.common.yml
      service: s3

  smtp:
    extends:
      file: docker-compose.common.yml
      service: smtp

  traefik:
    extends:
      file: docker-compose.common.yml
      service: traefik

  pgmaster:
    extends:
      file: docker-compose.common.yml
      service: pgmaster

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  migrations:
    extends:
      file: docker-compose.workers.yml
      service: migrations
    depends_on:
    - pgmaster
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster/bonde
    volumes:
    - ../server/migrations:/volumes

  api-rest:
    extends:
      file: docker-compose.apis.yml
      service: api-rest
    depends_on:
    - pgmaster

  api-graphql-deprecated:
    extends:
      file: docker-compose.apis.yml
      service: api-graphql-deprecated
    depends_on:
    - pgmaster

  api-graphql-custom:
    extends:
      file: docker-compose.apis.yml
      service: api-graphql-custom
    depends_on:
    - api-graphql

  api-graphql:
    extends:
      file: docker-compose.apis.yml
      service: api-graphql
    depends_on:
    - pgmaster
    - webhook-auth
    ports:
    - "5007:8080"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "segredo123"
      HASURA_GRAPHQL_AUTH_HOOK: http://webhook-auth:4001/hasura
      HASURA_GRAPHQL_AUTH_HOOK_MODE: "GET"
      WEBHOOK_MAIL_URL: http://webhook-mail:8080/webhook
      WEBHOOK_ACTIVISTS_PRESSURE_URL: http://webhook-activists:8080/webhook/pressure
      WEBHOOK_INVITATIONS_URL: http://webhook-auth:4001/invitations

  webhook-auth:
    extends:
      file: docker-compose.auth.yml
      service: webhook-auth
    environment:
      PORT: 4001
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql

  api-auth:
    extends:
      file: docker-compose.auth.yml
      service: api-auth
    environment:
      PORT: 4001
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql

  # listener-chatbot:
  #   extends:
  #     file: docker-compose.listeners.yml
  #     service: chatbot
  #   depends_on:
  #   - api-graphql
  #   environment:
  #     PORT: 5000
  #     APP_DOMAIN: http://chatbot.bonde.devel
  #   labels:
  #     traefik.frontend.rule: Host:chatbot.bonde.devel
  #     traefik.port: '5000'
  #     traefik.enable: 'true'

  # pipeline-registries-to-zendesk:
  #   extends:
  #     file: docker-compose.pipelines.yml
  #     service: registries-to-zendesk
  #   depends_on:
  #   - api-graphql

  # listener-notifications:
  #   extends:
  #     file: docker-compose.listeners.yml
  #     service: notifications
  #   depends_on:
  #   - api-graphql
  #   - smtp

  # pipeline-activists-to-notifications:
  #   extends:
  #     file: docker-compose.pipelines.yml
  #     service: activists-to-notifications
  #   depends_on:
  #   - api-graphql

  # listener-redes:
  #   extends:
  #     file: docker-compose.listeners.yml
  #     service: redes
  #   depends_on:
  #   - api-graphql

  # listener-redes-geolocation:
  #   extends:
  #     file: docker-compose.listeners.yml
  #     service: redes-geolocation
  #   depends_on:
  #   - api-graphql