version: '2'
volumes:
  datascience:
    driver: local
  redis_data:
    driver: local
  s3_data:
    driver: local
  pgmaster_data:
    driver: local
services:
  redis:
    image: redis:3
    volumes:
    - redis_data:/var/lib/redis
    ports:
    - 6379:6379/tcp
    command:
    - redis-server
    - --appendonly
    - 'yes'
  s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    volumes:
    - s3_data:/data
    ports:
    - 9000:9000/tcp
    command:
    - server
    - /data
    labels:
      traefik.frontend.rule: Host:fake-s3.bonde.devel
      traefik.port: '9000'
      traefik.enable: 'true'
      traefik.alias: fake-s3
  smtp:
    image: mailhog/mailhog
    environment:
      MH_HOSTNAME: smtp.bonde.devel
    ports:
    - 1025:1025/tcp
    - 8025:8025/tcp
    labels:
      traefik.frontend.rule: Host:fake-smtp.bonde.devel
      traefik.port: '8025'
      traefik.enable: 'true'
      traefik.alias: fake-smtp
  traefik:
    image: traefik:alpine
    environment:
      AWS_ACCESS_KEY_ID: xxxxxxx
      AWS_SECRET_ACCESS_KEY: xxxxxx
      AWS_REGION: us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./lb/traefik.toml:/traefik.toml"
    ports:
    - 80:80/tcp
    - 8080:8080/tcp
    - 443:443/tcp
    command:
    - --configfile=/traefik.toml
    labels:
      traefik.frontend.rule: Host:traefik.bonde.devel
      traefik.alias: traefik
      traefik.port: '8080'
      traefik.enable: 'true'
  pgmaster:
    image: postgres:9
    environment:
      POSTGRES_DB: monkey_db
      POSTGRES_PASSWORD: monkey_pass
      POSTGRES_USER: monkey_user
      PGDATA: /var/lib/postgresql/data
    volumes:
    - pgmaster_data:/var/lib/postgresql/data
    ports:
    - 5432/tcp
  assets-images:
    image: h2non/imaginary
    environment:
      PORT: '9009'
    stdin_open: true
    tty: true
    ports:
    - 9009:9000/tcp
    command:
    - -cors
    - -gzip
    - -concurrency
    - '10'
    - -enable-url-source
    labels:
      traefik.frontend.rule: Host:img.bonde.devel
      traefik.enable: 'true'
      traefik.alias: img
      traefik.port: '9009'
      io.rancher.container.pull_image: always



  datascience:
    build: datascience
    image: nossas/bonde-datascience
    volumes:
     - "datascience:/home/jovyan/work"
    ports:
     - "8888"
    labels:
      traefik.frontend.rule: Host:datascience.bonde.devel
      traefik.enable: 'true'
      traefik.port: '888'
