version: '2'
services:
  chatbot:
    image: nossas/bonde-bot:develop
    # build: ../chatbot
    environment:
      API_URL: http://api-v1:3000
      APP_DOMAIN: http://beta.bonde.devel
      GRAPHQL_URL: http://api-v2:3002/graphql
      JWT_TOKEN: xxxxxxxxx
      PORT: '5000'
      REDIS_URL: redis://redis:6379
      SPEECH_VERSION: v1
      WIT_SERVER_ACCESS_TOKEN: xxxxxxxxx
    external_links:
    - redis
    - api-v2
    - api-v1

  phone:
    image: nossas/bonde-phone:1.1.0
    # build: ../phone
    environment:
      AMOUNT: '100'
      APP_DOMAIN: http://phone.bonde.devel
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster:5432/bonde
      DEBUG: '0'
      ENABLE_TWILIO_CALL: '1'
      PORT: '5000'
      TWILIO_ACCOUNT_SID: sid
      TWILIO_AUTH_TOKEN: token
      TWILIO_NUMBER: '+999999999999'
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    ports:
    - 3003:5000/tcp
    command:
    - yarn
    - run
    - dev
    labels:
      traefik.frontend.rule: Host:phone.bonde.devel
      traefik.enable: 'true'
      traefik.alias: phone
      traefik.port: '5000'
      traefik.acme: 'false'
      traefik.frontend.entryPoints: http

  maquinista:
    image: nossas/bonde-maquinista:develop
    # build: ../maquinista
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster:5432/bonde
      HUBOT_AUTH_ADMIN: userexist
      HUBOT_GOOGLE_CSE_ID: id
      HUBOT_GOOGLE_CSE_KEY: key
      HUBOT_GOOGLE_SAFE_SEARCH: '''off'''
      HUBOT_NEWRELIC_ACCOUNT_ID: id
      HUBOT_NEWRELIC_API_KEY: ''
      HUBOT_SENDGRID_KEY: key
      HUBOT_SENDGRID_USER: apikey
      HUBOT_SLACK_TOKEN: token
      HUBOT_UPTIMEROBOT_APIKEY: apikey
      PORT: '8088'
      REDIS_URL: redis://redis:6379/hubot
      SECRET: secret
    external_links:
    - common/redis3:redis
    labels:
      traefik.frontend.rule: Host:maquinista.bonde.devel
      traefik.enable: 'true'
      traefik.alias: maquinista
      traefik.port: '8088'
      traefik.acme: 'false'
      traefik.frontend.entryPoints: http

  zendesk-mapa-v1:
    image: nossas/bonde-zendesk:develop
    # build: ../zendesk-mapa-v1
    environment:
      ZENDESK_ORGANIZATIONS: '{"Advogada":"","MSR":"","Psicologa":""}'
      ZENDESK_API_ROOT: http://xxxx.zendesk.com/api/v2/
      ZENDESK_API_TOKEN: token
      ZENDESK_API_USER: email@email.com.br
      JWT_SECRET: asd
      GOOGLE_MAPS_API_KEY: vcxz
      SENDGRID_SEND_EMAIL: email@email.com.br
      DEBUG: '0'
      SENDGRID_API_KEY: key
    command:
    - ./run_webserver.sh
    labels:
      traefik.frontend.rule: Host:webhook-mapa-zendesk.bonde.devel
      traefik.port: '5000'
      traefik.enable: 'true'

  graphql-auth:
    # image: nossas/bonde-webhooks-auth:develop
    image: nossas/bonde-webhooks-auth:feature-webhooks-auth
    # build:
    #   context: ./../bonde-microservices
    #   dockerfile: packages/webhooks-auth/Dockerfile
    environment:
      NODE_ENV: development
      DEBUG: webhooks-auth
      JWT_SECRET: segredo123

  chatbot:
    # image: nossas/bonde-bot:develop
    image: nossas/bonde-bot:feature-beta-graphene
    # build:
    #   context: ./../bonde-bot
    environment:
      API_URL: http://api-v1:3000
      REDIS_URL: redis://redis:6379
      SPEECH_VERSION: v1
      WIT_SERVER_ACCESS_TOKEN: xxxxxxxxx
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
    external_links:
    - redis
    - api-graphql
    - api-v1