version: '2'
services:
  webhook-phone:
    image: nossas/bonde-phone:1.1.0
    # build: ../phone
    environment:
      AMOUNT: '100'
      APP_DOMAIN: http://webhook-phone.bonde.devel
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster:5432/bonde
      DEBUG: '0'
      ENABLE_TWILIO_CALL: '1'
      PORT: '5000'
      TWILIO_ACCOUNT_SID: sid
      TWILIO_AUTH_TOKEN: token
      TWILIO_NUMBER: '+999999999999'
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    ports:
    - 3003:5000/tcp
    command:
    - yarn
    - run
    - dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-phone.rule=Host(`webhook-phone.bonde.devel`)
      - traefik.http.services.webhook-phone.loadbalancer.server.port=5000

  webhook-accounts:
    image: nossas/bonde-accounts:0.3.3
    environment:
      DEBUG: bonde-accounts-webhook
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      NODE_ENV: production
      PORT: '4001'
      JWT_SECRET: segredo123
      ACCOUNTS_LOGIN_URL: http://accounts.bonde.devel/login
      ACCOUNTS_REGISTER_URL: http://accounts.bonde.devel/register
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - bonde-accounts-webhook
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-accounts.rule=Host(`webhook-accounts.bonde.devel`)
      - traefik.http.services.webhook-accounts.loadbalancer.server.port=4001

  webhook-mail:
    image: nossas/bonde-webhooks-mail:0.2.2
    environment:
      DEBUG: webhook-mail*
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      PORT: '80'
      SMTP_HOST: smtp
      SMTP_PASS: 1
      SMTP_PORT: '1025'
      SMTP_USER: apikey
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-mail.rule=Host(`webhook-mail.bonde.devel`)
      - traefik.http.services.webhook-mail.loadbalancer.server.port=80

  solidarity-count:
    image: nossas/mapa-do-acolhimento:1.4.3
    environment:
      COMMUNITY_ID: '40'
      DEBUG: webhooks-solidarity-count*
      GOOGLE_MAPS_API_KEY: AI
      HASURA_API_URL: https://api-graphql:8080/v1/graphql
      MAUTIC_API_URL: https://mautic.bonde.devel/api
      MAUTIC_PASSWORD: 'segredo123'
      MAUTIC_USERNAME: email@domain.com
      NODE_ENV: production
      PORT: '80'
      WIDGET_IDS: '{"ADVOGADA": 17633, "PSICOLOGA": 17628, "MSR": 16850}'
      X_HASURA_ADMIN_SECRET: segreedo123
      ZENDESK_API_TOKEN: 8J
      ZENDESK_API_URL: https://zendesk.com/api/v2/
      ZENDESK_API_USER: email@domain.com/token
      ZENDESK_ORGANIZATIONS: '{"A":"3","M":"3","P":"3"}'
    command:
    - pnpm
    - --filter
    - bonde-webhooks-solidarity-count
    - run
    - start
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-solidarity-count.rule=Host(`webhook-solidarity-count.bonde.devel`)
      - traefik.http.services.webhook-solidarity-count.loadbalancer.server.port=80

  webhook-mautic-registry:
    image: nossas/mapa-do-acolhimento:1.4.3
    environment:
      DEBUG: webhooks-registry
      ELASTIC_APM_ACTIVE: 'false'
      HASURA_API_URL: https://api-graphql.bonde.devel/v1/graphql
      PORT: '8081'
      X_HASURA_ADMIN_SECRET: segreedo123
    stdin_open: true
    external_links:
    - common/redis3:redis
    tty: true
    command:
    - pnpm
    - --filter
    - bonde-webhooks-mautic-registry
    - run
    - start
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-mautic-registry.rule=Host(`webhook-mautic-registry.bonde.devel`)
      - traefik.http.services.webhook-mautic-registry.loadbalancer.server.port=8081

  webhook-mautic-zendesk:
    image: nossas/mapa-do-acolhimento:1.4.3
    environment:
      COMMUNITY_ID: '40'
      DEBUG: webhooks-zendesk*
      ELASTIC_APM_ACTIVE: 'false'
      GOOGLE_MAPS_API_KEY: A
      HASURA_API_URL: http://api-graphql:8080/v1/graphql
      MAUTIC_API_URL: http://mautic/api
      MAUTIC_PASSWORD: 'xxxx'
      MAUTIC_USERNAME: email@domain.com
      NODE_ENV: production
      PORT: '80'
      WIDGET_IDS: 2760,16835,17628,8190,16838,17633
      X_HASURA_ADMIN_SECRET: segreedo123
      ZENDESK_API_TOKEN: 8
      ZENDESK_API_URL: https://org.zendesk.com/api/v2/
      ZENDESK_API_USER: email@domain.com/token
      ZENDESK_ORGANIZATIONS: '{"ADVOGADA":"360269610652","MSR":"360273031591","PSICÓLOGA":"360282119532"}'
    command:
    - pnpe
    - --filter
    - bonde-webhooks-mautic-zendesk
    - run
    - start
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-mautic-zendesk.rule=Host(`webhook-mautic-zendesk.bonde.devel`)
      - traefik.http.services.webhook-mautic-zendesk.loadbalancer.server.port=80


  webhook-match-otimizado:
    image: nossas/mapa-do-acolhimento:0.4.9
    environment:
      COMMUNITY_ID: '22'
      HASURA_API_URL: http://api-graphql:8080/v1/graphql
      PORT: '5000'
      REACT_APP_DOMAIN_CROSS_STORAGE: http://localhost:5003
      REACT_APP_ENVIRONMENT: production
      REACT_APP_GOOGLE_CLIENT_KEY: A
      REACT_APP_LOGIN_URL: http://localhost:5000/auth/login
      REACT_APP_ZENDESK_ORGANIZATIONS: '{"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}'
      X_HASURA_ADMIN_SECRET: segredo123
      ZENDESK_API_TOKEN: e
      ZENDESK_API_URL: https://org.zendesk.com/api/v2/
      ZENDESK_API_USER: email@domain.com
    command:
    - pnpm
    - --filter
    - client-solidarity
    - run
    - start
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-match-otimizado.rule=Host(`webhook-match-otimizado.bonde.devel`)
      - traefik.http.services.webhook-match-otimizado.loadbalancer.server.port=5000

  webhook-beta:
    image: nossas/bonde-bot-beta:3.1.8
    environment:
      API_URL: http://api-rest:3000
      APP_DOMAIN: http://webhook-beta.bonde.devel
      ELASTIC_APM_ACTIVE: 'false'
      FORM_MOBILIZATION_ID: '1305'
      FORM_WIDGET_ID: '23416'
      GRAPHQL_URL: http://api-graphql-deprecated:3002/graphql
      JWT_TOKEN: e
      NODE_ENV: production
      PORT: '5000'
      REDIS_URL: redis://redis:6379
      SPEECH_VERSION: v2
      WIT_SERVER_ACCESS_TOKEN: M
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-beta.rule=Host(`webhook-beta.bonde.devel`)
      - traefik.http.services.webhook-beta.loadbalancer.server.port=5000

  webhook-chatbot:
    image: nossas/bonde-bot-chatbot:3.1.8
    environment:
      API_URL: http://api-rest:3000
      APP_DOMAIN: https://webhook-chatbot.bonde.devel
      ELASTIC_APM_ACTIVE: 'false'
      GRAPHQL_URL: https://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      JWT_TOKEN: e
      NODE_ENV: production
      PORT: '5000'
      REDIS_URL: redis://redis3:6379
      SPEECH_VERSION: v2
      WIT_SERVER_ACCESS_TOKEN: M
      WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-chatbot.rule=Host(`webhook-chatbot.bonde.devel`)
      - traefik.http.services.webhook-chatbot.loadbalancer.server.port=5000
