version: '2'

volumes:
  redis_data:
    driver: local
  s3_data:
    driver: local
  pgmaster_data:
    driver: local

services:
  s3:
    extends:
      file: docker-compose.common.yml
      service: s3

  smtp:
    extends:
      file: docker-compose.common.yml
      service: smtp

  traefik:
    extends:
      file: docker-compose.common.yml
      service: traefik

  pgmaster:
    extends:
      file: docker-compose.common.yml
      service: pgmaster

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  migrations:
    extends:
      file: docker-compose.workers.yml
      service: migrations
    depends_on:
    - pgmaster
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster/bonde
    volumes:
    - ../workers/migrations:/volumes
