version: '2'
services:
  mob-generator:
    image: nossas/bonde-experiments-mob-generator:0.1.2
    environment:
      API_REST_TOKEN: e
      API_REST_URL: http://api-rest:3000
      COMMUNITY_ID: '271'
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      SMTP_HOST: smtp
      SMTP_PASS: admin
      SMTP_PORT: '1025'
      SMTP_USER: admin
      WIDGET_ID: '25662'
      WIDGET_METADATA: '{"form_mapping":[{"uid":"field-1588860958854-55","name":"first_name"},{"uid":"field-1588860971126-48","name":"last_name"},{"uid":"field-1588860996818-24","name":"email"},{"uid":"field-1588861040051-78","name":"celular"},{"uid":"field-1588861063724-23","name":"state"},{"uid":"field-1588861176318-77","name":"institution_type"},{"uid":"field-1588861198345-77","name":"institution_name"},{"uid":"field-1588937321911-11","name":"slug"}]}'
      WS_GRAPHQL_URL: wss://api-graphql:8080/v1/graphql
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - listener-mob-generator

  match:
    image: nossas/mapa-do-acolhimento:1.4.3
    environment:
      COMMUNITY_ID: '40'
      GOOGLE_MAPS_API_KEY: A
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      WS_GRAPHQL_URL: wss://api-graphql:8080/v1/graphql
      ZENDESK_API_TOKEN: S
      ZENDESK_API_URL: https://org.zendesk.com/api/v2/
      ZENDESK_API_USER: email@domain.com
      ZENDESK_ORGANIZATIONS: '{"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}'
    command:
    - pnpm
    - --filter
    - listener-match
    - run
    - start

  redes:
    image: nossas/bonde-redes:2.1.2
    environment:
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - listener-redes
    labels:
      io.rancher.container.pull_image: always

  solidarity:
    image: nossas/mapa-do-acolhimento:1.4.3
    environment:
      COMMUNITY_ID: '40'
      GOOGLE_MAPS_API_KEY: A
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      LAWYER_WIDGET_IDS: 8190,16838,17633
      MAUTIC_API_URL: http://mautic:5000/api
      MAUTIC_PASSWORD: 'xxx'
      MAUTIC_USERNAME: email@domain.com
      THERAPIST_WIDGET_IDS: 2760,16835,17628
      WS_GRAPHQL_URL: wss://api-graphql:8080/v1/graphql
      ZENDESK_API_TOKEN: S
      ZENDESK_API_URL: https://org.zendesk.com/api/v2/
      ZENDESK_API_USER: email@domain.com
      ZENDESK_ORGANIZATIONS: '{"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}'
    command:
    - pnpm
    - --filter
    - listener-solidarity
    - run
    - start

  redes-geolocation:
    image: nossas/bonde-redes:2.1.2
    environment:
      GOOGLE_MAPS_API_KEY: A
      GRAPHQL_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      WS_GRAPHQL_URL: ws://api-graphql:8080/v1/graphql
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - listener-redes-geolocation
