version: '2'

volumes:
  redis_data:
    driver: local
  s3_data:
    driver: local
  pgmaster_data:
    driver: local

services:
  s3:
    extends:
      file: docker-compose.common.yml
      service: s3

  smtp:
    extends:
      file: docker-compose.common.yml
      service: smtp

  traefik:
    extends:
      file: docker-compose.common.yml
      service: traefik

  pgmaster:
    extends:
      file: docker-compose.common.yml
      service: pgmaster

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  migrations:
    extends:
      file: docker-compose.workers.yml
      service: migrations
    depends_on:
    - pgmaster
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster/bonde
    volumes:
    - ./../bonde-migrations/:/volumes

  api-rest:
    extends:
      file: docker-compose.apis.yml
      service: api-rest
    depends_on:
    - pgmaster
    labels:
      traefik.frontend.rule: Host:api-rest.bonde.devel
      traefik.port: '3000'
      traefik.enable: 'true'
      traefik.alias: api-rest

  api-v2:
    extends:
      file: docker-compose.apis.yml
      service: api-v2
    depends_on:
    - pgmaster

  api-graphql:
    extends:
      file: docker-compose.apis.yml
      service: api-graphql
    depends_on:
    - pgmaster
    - api-v2
    - graphql-auth
    ports:
    - "5007:8080"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "segredo123"
      HASURA_GRAPHQL_AUTH_HOOK: http://graphql-auth:4001/webhook
      HASURA_GRAPHQL_AUTH_HOOK_MODE: "GET"
    labels:
      traefik.frontend.rule: Host:api-graphql.bonde.devel
      traefik.enable: 'true'
      traefik.alias: api-graphql
      traefik.port: '8080'

  graphql-auth:
    extends:
      file: docker-compose.webhooks.yml
      service: graphql-auth
    environment:
      PORT: 4001
    labels:
      traefik.frontend.rule: Host:graphql-auth.bonde.devel
      traefik.port: '4001'
      traefik.enable: 'true'

  chatbot:
    extends:
      file: docker-compose.webhooks.yml
      service: chatbot
    depends_on:
    - api-graphql
    environment:
      PORT: 5000
      APP_DOMAIN: http://chatbot.bonde.devel
      JWT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiY29tbW9uX3VzZXIiLCJ1c2VyX2lkIjoxLCJpYXQiOjE1NjgxMjAxMzQsImV4cCI6MTU2ODIwNjUzNCwiYXVkIjoicG9zdGdyYXBoaWxlIiwiaXNzIjoicG9zdGdyYXBoaWxlIn0.I52gMRQ8CpOAjRTkxBBHVC-qH6Mnll87ah2wdVgbLw0
    labels:
      traefik.frontend.rule: Host:chatbot.bonde.devel
      traefik.port: '5000'
      traefik.enable: 'true'

  webhooks-registry:
    build: node-pnpm.dockerfile
    extends:
      file: docker-compose.webhooks.yml
      service: webhooks-registry
    working_dir: /usr/src/app/packages/webhooks-registry
    volumes: 
      - ../bonde-microservices:/usr/src/app
    tty: true
    command:
    - pnpm
    - run
    - dev
    depends_on:
    - api-graphql
    ports: 
    - 8081:80

  webhooks-zendesk:
    build: node-pnpm.dockerfile
    extends:
      file: docker-compose.webhooks.yml
      service: webhooks-zendesk
    working_dir: /usr/src/app/packages/webhooks-zendesk
    volumes: 
      - ../bonde-microservices:/usr/src/app
    tty: true
    command:
    - pnpm
    - run
    - dev
    depends_on:
    - api-graphql

  webhooks-solidarity-count:
    build: node-pnpm.dockerfile
    extends:
      file: docker-compose.webhooks.yml
      service: webhooks-solidarity-count
    working_dir: /usr/src/app/packages/webhooks-solidarity-count
    volumes: 
      - ../bonde-microservices:/usr/src/app
    tty: true
    user: "${UID}:${GID}"
    command:
    - pnpm
    - run
    - dev
    depends_on:
    - api-graphql
    ports:
    - 8084:80

  webhooks-solidarity-match:
    build: node-pnpm.dockerfile
    extends:
      file: docker-compose.webhooks.yml
      service: webhooks-solidarity-match
    working_dir: /usr/src/app/packages/webhooks-solidarity-match
    volumes: 
      - ../bonde-microservices:/usr/src/app
    tty: true
    command:
    - pnpm
    - run
    - dev
    depends_on: 
    - api-graphql