version: '2'

services:

  api-rest:
    image: nossas/bonde-server:develop
    # build: ../server/api-rest
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_BUCKET: bonde
      AWS_ID: admin
      AWS_ROUTE53_REGION: sa-east-1
      AWS_ROUTE53_SYNC: force
      AWS_ROUTE_IP: 127.0.0.1
      AWS_SECRET: password
      AWS_SECRET_ACCESS_KEY: password
      CLIENT_APP_NAME: hub-client
      CLIENT_HOST: bonde.devel
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster/bonde
      JWT_SECRET: segredo123
      JWT_TYPE: postgraphql.jwt_token
      MAILCHIMP_API_KEY: 111111-us6
      MAILCHIMP_GROUP_ID: '11'
      MAILCHIMP_LIST_ID: 111111ac
      NEW_RELIC_LICENSE_KEY: 1111111
      NEW_RELIC_LOG: stdout
      NO_VHOST: '0'
      ORG_RECIPIENT_ID: xxxxxx
      PAGARME_API_KEY: ak_test_jC4dmaMT3njyVuGQomvbMQfvNUjn71
      PORT: '3000'
      RAILS_ENV: staging
      RAILS_SERVE_STATIC_FILES: enabled
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: xxxxxx
      SENTRY_DSN: https://xxxxx:xxxxx@sentry.io/121379
      SMTP_HOST: smtp
      SMTP_PASSWORD: xxxxxxxx
      SMTP_PORT: '1025'
      SMTP_USERNAME: xxxxxx
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    command:
    - bundle
    - exec
    - puma
    - -C
    - config/puma.rb
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-rest.rule=Host(`api-rest.bonde.devel`)
      - traefik.http.services.api-graphql-deprecated.loadbalancer.server.port=3000
      
  api-graphql-deprecated:
    image: nossas/bonde-graphql:develop
    # build: ../server/deprecated-api-graphql/
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster/bonde
      JWT_SECRET: segredo123
      JWT_TYPE: postgraphql.jwt_token
      NEW_RELIC_ENABLED: 'false'
      PG_DEFAULT_ROLE: anonymous
      PORT: '3002'
      SCHEMA_NAME: postgraphql
      SENTRY_DSN: https://xxxxx:xxxxx@sentry.io/142717
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    command:
    - npm
    - run
    - dev
    ports:
      - 3002:3002/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-graphql-deprecated.rule=Host(`api-graphql-deprecated.bonde.devel`)
      - traefik.http.services.api-graphql-deprecated.loadbalancer.server.port=3002

  api-graphql:
    image: hasura/graphql-engine
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster:5432/bonde
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: "segredo123"
      SCHEMA_API_V2_URL: http://api-graphql-deprecated:3002/graphql
      SCHEMA_API_AUTH_URL: http://api-graphql-custom:4001/graphql
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-graphql.rule=Host(`api-graphql.bonde.devel`)
      - traefik.http.services.api-graphql.loadbalancer.server.port=8080

  api-graphql-custom:
    image: nossas/bonde-apis
    # build: ../server/api-graphql
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-graphql-custom.rule=Host(`api-graphql-custom.bonde.devel`)
      - traefik.http.services.api-graphql-custom.loadbalancer.server.port=3002
  