version: '2'
services:

  api-rest:
    image: nossas/bonde-server:develop
    # build: ../server/api-rest
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_BUCKET: bonde
      AWS_ID: admin
      AWS_ROUTE53_REGION: sa-east-1
      AWS_ROUTE53_SYNC: force
      AWS_ROUTE_IP: 127.0.0.1
      AWS_SECRET: password
      AWS_SECRET_ACCESS_KEY: password
      CLIENT_APP_NAME: hub-client
      CLIENT_HOST: bonde.devel
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster/bonde
      JWT_SECRET: segredo123
      JWT_TYPE: postgraphql.jwt_token
      MAILCHIMP_API_KEY: 111111-us6
      MAILCHIMP_GROUP_ID: '11'
      MAILCHIMP_LIST_ID: 111111ac
      NEW_RELIC_LICENSE_KEY: 1111111
      NEW_RELIC_LOG: stdout
      NO_VHOST: '0'
      ORG_RECIPIENT_ID: xxxxxx
      PAGARME_API_KEY: ak_test_
      PORT: '3000'
      RAILS_ENV: staging
      RAILS_SERVE_STATIC_FILES: enabled
      REDIS_URL: redis://redis:6379
      SECRET_KEY_BASE: xxxxxx
      SENTRY_DSN: https://xxxxx:xxxxx@sentry.io/121379
      SMTP_HOST: smtp
      SMTP_PASSWORD: xxxxxxxx
      SMTP_PORT: '1025'
      SMTP_USERNAME: xxxxxx
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    command:
    - bundle
    - exec
    - puma
    - -C
    - config/puma.rb
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-rest.rule=Host(`api-rest.bonde.devel`)
      - traefik.http.services.api-graphql-deprecated.loadbalancer.server.port=3000

  api-graphql-deprecated:
    image: nossas/bonde-graphql:develop
    # build: ../server/deprecated-api-graphql/
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster/bonde
      JWT_SECRET: segredo123
      JWT_TYPE: postgraphql.jwt_token
      NEW_RELIC_ENABLED: 'false'
      PG_DEFAULT_ROLE: anonymous
      PORT: '3002'
      SCHEMA_NAME: postgraphql
      SENTRY_DSN: https://xxxxx:xxxxx@sentry.io/142717
      WEB_CONCURRENCY: '1'
      WEB_MEMORY: '256'
    command:
    - npm
    - run
    - dev
    ports:
      - 3002:3002/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-graphql-deprecated.rule=Host(`api-graphql-deprecated.bonde.devel`)
      - traefik.http.services.api-graphql-deprecated.loadbalancer.server.port=3002

  api-graphql:
    image: hasura/graphql-engine
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster:5432/bonde
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: "segredo123"
      HASURA_GRAPHQL_AUTH_HOOK: http://webhook-accounts:4001/hasura
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
      WEBHOOK_MAIL_URL: http://webhook-mail/webhook
      WEBHOOK_ACTIVISTS_PRESSURE_URL: http://webhook-activists:3000/webhook/pressure
      SCHEMA_API_V2_URL: http://api-graphql-deprecated:3002/graphql
      SCHEMA_API_AUTH_URL: http://api-accounts:4001/graphql
      WEBHOOK_INVITATIONS_URL: http://webhook-accounts:3000/invitations
      SCHEMA_API_ACTIVISTS_URL: http://api-activists:3000/graphql
      SCHEMA_API_NOTIFICATIONS_URL: http://api-notifications:3000/graphql
      SCHEMA_API_DOMAINS_URL: http://api-domains:3000/graphql
      SCHEMA_API_PAYMENTS_URL: http://api-payments:3000/graphql
      SCHEMA_API_REDES_URL: http://api-redes:3000/graphql
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-graphql.rule=Host(`api-graphql.bonde.devel`)
      - traefik.http.services.api-graphql.loadbalancer.server.port=8080

  api-graphql-custom:
    image: nossas/bonde-apis:0.0.7
    # build: ../server/api-graphql
    environment:
      GRAPHQL_HTTP_URL: http://api-graphql.bonde.devel/v1/graphql
      HASURA_SECRET: segredo123
      HOST: 0.0.0.0
      JWT_SECRET: segredo123
      PAGARME_API_KEY: ak_test_
      PORT: '3000'
    # command: pnpm m run start
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.api-graphql-custom.rule=Host(`api-graphql-custom.bonde.devel`)
    #   - traefik.http.services.api-graphql-custom.loadbalancer.server.port=3002

  api-payments:
    image: nossas/bonde-apis:0.0.7
    environment:
      GRAPHQL_HTTP_URL: http://api-graphql.bonde.devel/v1/graphql
      HASURA_SECRET: segredo123
      HOST: 0.0.0.0
      JWT_SECRET: segredo123
      PAGARME_API_KEY: ak_test_
      PORT: '3000'
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - payments-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-payments.rule=Host(`api-payments.bonde.devel`)
      - traefik.http.services.api-payments.loadbalancer.server.port=3000

  api-domains:
    image: nossas/bonde-apis:0.0.7
    environment:
      AWS_ACCESS_KEY: A
      AWS_ROUTE53_REGION: sa-east-1
      AWS_ROUTE_IP: 127.0.0.1
      AWS_SECRET_KEY: L
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      HOST: 0.0.0.0
      JWT_SECRET: segredo123
      PORT: '3000'
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - domains-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-domains.rule=Host(`api-domains.bonde.devel`)
      - traefik.http.services.api-domains.loadbalancer.server.port=3000

  api-activists:
    image: nossas/bonde-apis:0.0.7
    environment:
      GRAPHQL_HTTP_URL: http://api-graphql.bonde.devel/v1/graphql
      HASURA_SECRET: segredo123
      HOST: 0.0.0.0
      PORT: '3000'
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - activists-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-activists.rule=Host(`api-activists.bonde.devel`)
      - traefik.http.services.api-activists.loadbalancer.server.port=3000

  api-redes:
    image: nossas/bonde-apis:0.0.7
    environment:
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      HOST: 0.0.0.0
      JWT_SECRET: segredo123
      PORT: '3000'
      ZENDESK_API_TOKEN: 8
      ZENDESK_API_URL: https://org.zendesk.com/api/v2/
      ZENDESK_API_USER: email@domain.com
      ZENDESK_ORGANIZATIONS: '{"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}'
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - redes-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-redes.rule=Host(`api-redes.bonde.devel`)
      - traefik.http.services.api-redes.loadbalancer.server.port=3000

  api-accounts:
    image: nossas/bonde-apis:0.0.7
    environment:
      ACCOUNTS_REGISTER_URL: http://accounts.bonde.devel/register
      GRAPHQL_HTTP_URL: http://api-graphql:8080/v1/graphql
      HASURA_SECRET: segredo123
      HOST: 0.0.0.0
      JWT_SECRET: segredo123
      LOG_LEVEL: debug
      PORT: '4001'
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - accounts-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-accounts.rule=Host(`api-accounts.bonde.devel`)
      - traefik.http.services.api-accounts.loadbalancer.server.port=3000

  api-notifications:
    extends:
      service: api-graphql-custom
    environment:
      HOST: 0.0.0.0
      PORT: '3000'
      SENDGRID_API_KEY: SG
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - notifications-api
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-notifications.rule=Host(`api-notifications.bonde.devel`)
      - traefik.http.services.api-notifications.loadbalancer.server.port=3000
