version: '2'

services:

  webhook-auth:
    image: nossas/bonde-auth-webhook:develop
    # build:
    #   context: ../server/api-graphql
    #   dockerfile: packages/webhook/Dockerfile
    environment:
      NODE_ENV: development
      DEBUG: bonde-auth-webhook
      JWT_SECRET: segredo123
      HASURA_SECRET: segredo123
    labels:
      - traefik.enable=true
      - traefik.http.routers.webhook-auth.rule=Host(`webhook-auth.bonde.devel`)
      - traefik.http.services.webhook-auth.loadbalancer.server.port=4001

  api-auth:
    image: nossas/bonde-auth-api:develop
    # build:
    #   context: ../server/api-graphql
    #   dockerfile: packages/api/Dockerfile
    environment:
      NODE_ENV: development
      DEBUG: bonde-auth-api
      JWT_SECRET: segredo123
      HASURA_SECRET: segredo123
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-auth.rule=Host(`api-auth.bonde.devel`)
      - traefik.http.services.api-auth.loadbalancer.server.port=4001