logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]
sendAnonymousUsage = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = """-----BEGIN CERTIFICATE-----
MIIFrjCCA5YCCQCkDQMrrFrpHjANBgkqhkiG9w0BAQsFADCBmDELMAkGA1UEBhMC
QlIxCzAJBgNVBAgMAlJKMRcwFQYDVQQHDA5SaW8gZGUgSmFuZWlybzEPMA0GA1UE
CgwGTm9zc2FzMQ4wDAYDVQQLDAVCb25kZTEiMCAGA1UEAwwZYm9uZGUuZGV2ZWws
Ki5ib25kZS5kZXZlbDEeMBwGCSqGSIb3DQEJARYPdGVjaEBub3NzYXMub3JnMB4X
DTE4MDQxMDAxNTExMVoXDTE5MDQxMDAxNTExMVowgZgxCzAJBgNVBAYTAkJSMQsw
CQYDVQQIDAJSSjEXMBUGA1UEBwwOUmlvIGRlIEphbmVpcm8xDzANBgNVBAoMBk5v
c3NhczEOMAwGA1UECwwFQm9uZGUxIjAgBgNVBAMMGWJvbmRlLmRldmVsLCouYm9u
ZGUuZGV2ZWwxHjAcBgkqhkiG9w0BCQEWD3RlY2hAbm9zc2FzLm9yZzCCAiIwDQYJ
KoZIhvcNAQEBBQADggIPADCCAgoCggIBAKkbAlvUMJjdSq3gJzXx2P4lotHwLORC
hdCUWTIUz6Wor3NhosfXNrJZI/Gbf9CZiSbz5gKo6CRijyhlukz3IidpXrxFtwGI
Edr2e+TJYAatMtZtI65LWw19qqRarXeXjto5Qhbs56V4SqqFBaVjvty3pb14/H8b
ILvL3+cNzpIh/WivoX/SXMUzWf2QPz5yYxc2Z3FZg9zi9qebJNgMFbFaliu+Cb7v
6cDCrQCUOIWye9gwBRhfzKkCCnmosAJhzUyDL7obzPvSvA3ixpfPuA3lPTekVnCu
49/iUICxWKaKZnF3sGGOc71pDzuFT3U51gZGEvWp2x8ZYbn4TI66azYcJyi4HtBl
c6kr+Cen3I5GQquXUi1LgFfkexdktiyAb5SstGNw7oEOe4p9NVtrmmdPDcpYKB13
Ye5CPkjX0IdqYGIazuWlb+V4xhrKiH2/9PliZHfApuMZKv/WbhMJ9uPDY1mPzzdJ
G2y3/UZ30uu3eY0anhvfExD7g7rSMdfgzn6jeItyFsurw+P+naHotvBLEJzcpDBA
Cjg+DvX+OfpWbvqViTXfipiySbcXYrmaag7xjkWaIQKtt6Kd36uIiVolshmN9uKa
DPwuhinJzbjXQsD4F2Qe3VvMa50HmfRbkJ0AcnUIAfheqm2K1J8rYXBMGnyjgulB
63b5F575zitjAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAFCifEjEfoM9fa+8t7So
UBBp5kUbnaGv0qA4E5SNoUIKn1dO7y2mrtGn2oHlZ9O68ITGYsh6spslibCsvnRM
/6MckCpThJfr7+Px0HrXtOC/hFlXgLEA70iahZUgpxNz141jwIgbSGuOxoqMBcO5
ICWhVO8W0rY0/j1RWvWea5CAIEmTquKqiNwfE+wa+N5+nuYzTA/Jr3P6GhkP5fak
ukp0RHsAPxXMw3IaZ6gMLdf0/ctjspSseis2E0+wUZmzTtown5ibO9dWMYXpTWJ9
rprm0eXeG2YXk0UY6tKjbMnEFm/d5yTuwZlyKodiRnH/rQFOnVsXZ2QfVknopqCA
+ggrnpfcAgHDVU5j4GeQzF5FJJpyAuw+Y/pbtXrPQb5zbiIsKyXwY9lunA/hVKve
0cdwYi6GSLSMARsFY2fgkjVYhdFEISLw/7tAyZ/5XPA4jFOB6CJo+kurID5VNdW4
wncBspPccQakGoIxcNV41zKEMTOeP8tSVLVqmfTqOgQzoPxYrvN+LoVVmgdCSirb
HEg3mAuYz8/5zArFWY1rq08bHlDf5EdtyTTuXespDrhyENPn+tQYNNTwueOdycby
7VFMD+3K1jIukIfz+IJTY/STYkVZspUgMZsMZ9kFetAouxkAPKDYcVQLXcKjgKFA
TupgzypB5b7xx6lgIhEisx/Q
-----END CERTIFICATE-----"""
      keyFile = """-----BEGIN ENCRYPTED PRIVATE KEY-----
MIIJnzBJBgkqhkiG9w0BBQ0wPDAbBgkqhkiG9w0BBQwwDgQIOSPj/o+09RgCAggA
MB0GCWCGSAFlAwQBKgQQsKBJfMNJIIUA1YA5gNooZwSCCVDNTSA6VLow5QSFQjGm
jnQ8vdgKKseJLSGc9iqMTVl6Y70kt6Sr8/0Ynbbu5N88T4AFMXwkb9mvsjLIzP6U
LhDxLMVwgcy9hrfBfrgy/JFHwofHcBQXc34eELt/dCD5IxvxmHYxXPTwCSCjTxww
h6AZoyGZlX4H4g0zlWsWYumJJdT3YD0TAr6xgb7vRUBKOQ5E6P0iL5Z72bI1xOXb
mF5YjUXATjSBW5RlJaemv9NODmDjqoZFrDIPoGg/Mj+MF7xHLBGON1lL9wkG9bTA
wWcDVbphkK6osD08tTkX+AqDjHm140LVVLeqgjiZKZjXlFm9W4U3NdzjGMzZ4lSm
1EPPuiUqpd+k03R8QZ1tg5Hr9J+CC8bGyZDX3bJh5nJubS6Mmrhukwdje7qDplaU
42MoOZ3/ObrmyR3xkQDd8dBIE/MHYlinseZBGTJ1Qe8Hi4Wcxj8w3Q0dzmhpyyOk
g2FtffSTXZWYmDC49IXXJgLHlCcYWyE1FBTUe9sfp9YxlgsX93SdaylvqxykUaot
wKsctVDDk4UGgo2daSUsDLXd2H/n3B87GwLhb35nurWg2szKAgfs6MvvJ2wX7RLp
HvPN1lepywSyZV7T2GI4S1TPad7Rltp7lvyisKTIx7RiDwgMe+vMik1TGPwk/KlZ
4gv25Oj4W3X64kluIoLzNf5iuMWk7gxPa639y/Q6zEQM9dzirMWiln+D1S/kCkIg
gdEZudOIwkR1BRe6Dq7tVlejDQrSUGwJPTRgUQg5KsFbY3OWWxSuL23bbb+IbUpT
O6IvtIS0U2LWpmFwxScXfN+S1sTp8GEbH4ryswT54p6oY5s/DPhlwqskLUH/LAB6
0zER9IGHD8qw+1vMjqB39TMIVL6Lj7580zqMqMgaW/2EmeuzcYhANZM0zjzJwv8i
pZPXrfrjS7aVFaQAjw87DiMksF3i5fL1B5OgXFDWQFT5JECABtnpW+yzT8LNdzvB
SbuzO9UX+iEU+2E1GVj8KDHuUR1XkHTWO+rv8UcpBmPsDELK17yDP6EGLRlku0Ee
gz/SPiTQr3CYmkzVw15l1MASjf4jbpkJmaloYVBUBPnbXx8A5T34yR49a5mAhlwp
gO695mDOHVcNIxazFsZj86T+vKZVT4Qq2sJ9kIA3sc3VF7kPQ/EMAQmX53mhwEgr
kOsR6x7e1TZvWBv6+RC/We+1NS2Uf6jMdmm8aeZK3QED8/fCdGJA3HYir/S/wVgs
gHibAArUR8DxQOy2JtgQ8QEDyrzjCmyY+FjODqaXZ1TglHqo68HZe0slsX97oxte
Xw0G7uA32fDUAIeuZr62RjcdX5um2yX6rjgxonlahL6SVlbvgEyIZEP5jfIZg5PZ
3oTTbvlQddHVvVWLan6y+ZzfZAeq8Wd6AmIB9f/LmG7fq7IXPYyWhC9orYjmWTO+
7Ce+RXZ1B1gB7/TyuSVjhdKmv3dVrMZbCZNIV587M0CXFv/m12zriLQUr4w4G04r
ofczXnR45FnFDsxDsWnLJ5Vbm0YLcrrgVgJANlE0lx6oX+77uDRNNcBxAG1N+S+M
6vWuvz8NjtJd3RgtzkuFA2brgi/xHX4sD1O/+RFj4Fdw0Y1ZOkXjrt9E9rMGMy2M
gqIYsVdFu9JhrmzO+UlKSdDXXmDE4oI5+/asSJ2uUXauI6WcaJEIcl6651eH51MH
qMVOMLAyr+EpXI3WO5//gqVA9ONrjAhvhyQ0MayYDMcn5hwCyzjIuRgm/MDnVOYl
vHD8gMk9L1nYfDAwbMy6LqbUDwYY2vLWKQxlM2g/cBvPBIsy6Wt3qbf2azt3Nef0
kwFF08QGA9neGC9hOjk9dIK7Dbuk+Hg1AdQyOwy1NOnVxUR3NVf5+kxam6nywN2O
QjWXTNx2wlOegaVGagfniOniSmElmB7YGIqUJKuv/wXDZcioDsT5KWIftFNOdVFd
9oZZklJ0jCbCdi5mbziezhAossNzagld9Detg7QD4GwQsuR8FAZpV4qL0PUSQD12
jeeDzrT1AHNhwtAAvZcLSeuXOZP3DcGdefJQulFe8QAmzYpqSnlBpCUiu1oeP3Aa
sQo8MVnblefKaEaj1aa0BMlQCeKS346/6YvL/zuz/SUMZr+k+SXS8mU7ZzBaPljb
99aT7Q6rBWEf7gjm0w78H4Jw4FZkzs8auQYLN5F2CeyEOlyIbzGi7nzl3eiMJJql
lq0HLnuYlCgCkA8pd3feDX/17/S0GImutYf/X2HITSdqVqMr/TepjTYWbNwP0BRw
K5D5GztSFDb/FGLrzhwcDbvz1FLIKpbfbhdPy3u0ckihWn+3uqkEyV5IJLJT1X5O
MB5gbbZrVO+v0q3vtpfKHgOap1lTvT4jg80cshhkPzwb5o/FbxvAxE07HvuYb5T+
Htz6qTxDlWPX5EhOozyvCp2CRbcfVbkuN56MrTS20pQ+CL63UDgSNqF2AB6yc9ej
pmLppZdXe1UrOEdRLisR76gXW+Y+On2fULsxhc9IjPD0EOkRYQv0b4GCt+ulJtrI
sFCy2zRyUt+3/iLgDSuWFwz1qinn/CKbpMBl5d5FA8eqF34fjatlg+0ZOIriMsNj
K4l8ijg/F0zkZHp8g5kOooQli7PEQtSvtta1V0Panv7EJ5sKg3EeNdBW+tzAUIeT
rI7DRDvPy/SPslDQklWSCuWf5+zlHnIKbv/j8Dicrc9PXfMtYCOaB6Po/nCRwXkr
a/H72LHAf730Fo7E277gIcYfSTZeZSZIEpOFa/qaSH381dZH5C+pOsQjkFmEga7Y
we2rG0Oicdb3E8OPM1+XOUAsO7hh1HJ5e8cytj8T8j40WABkRRHS0lgBlcqo6eeF
P1BFIZcEBtpd/bnB0TRnPcNgLAGeleTvHY7ZDyqDLskdwKvGSn9jxYkZiTYKjMng
HrHL/K6DPh6UQ+yr1QC6n5uSzPwYTaH4b3UtiR/PUgAKgcY++pHLuD+jmWQZG/wP
9rtVhDdeVu6V3ON4y25Y1RraTc/iQh4KZO7BBr/C+w/7BsCdQ3Y2q9qZ5pFS06Jy
F4948rY304MPve5yHBMoT1+APDjmDzMUyCao2DtcPdGWRweJqkOuh9HJWKQBdzPy
KnQZf+RQBYoS3Qz7hL5nVGagJDAuxF+ukbfbZvWggGzza1EnC9s/zD8GUS2WiPWL
gyVvJFaLibTjisygfWi77klQkg==
-----END ENCRYPTED PRIVATE KEY-----"""


[acme]
email = "tech@bonde.devel"
storage = "traefik/acme/account"
entryPoint = "https"
OnHostRule = true
caServer = "https://acme-staging.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
  provider = "route53"
  delayBeforeCheck = 0

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "bonde.devel"
watch = true
exposedbydefault = false

[consul]
endpoint = "10.0.1.39:8500"
watch = true
prefix = "traefik"
