services:

  # mob-generator:
  #   image: nossas/bonde-experiments-mob-generator:0.1.2
  #   environment:
  #     API_REST_TOKEN: a1111
  #     API_REST_URL: http://api-rest.bonde.devel
  #     COMMUNITY_ID: 1
  #     GRAPHQL_URL: http://api-graphql.bonde.devel/v1/graphql
  #     HASURA_SECRET: a11111
  #     SMTP_HOST: smtp
  #     SMTP_PASS: a1111
  #     SMTP_PORT: 587
  #     SMTP_USER: apikey
  #     WIDGET_ID: 3123213
  #     WIDGET_METADATA: '{"form_mapping":[{"uid":"field-1588860958854-55","name":"first_name"},{"uid":"field-1588860971126-48","name":"last_name"},{"uid":"field-1588860996818-24","name":"email"},{"uid":"field-1588861040051-78","name":"celular"},{"uid":"field-1588861063724-23","name":"state"},{"uid":"field-1588861176318-77","name":"institution_type"},{"uid":"field-1588861198345-77","name":"institution_name"},{"uid":"field-1588937321911-11","name":"slug"}]}'
  #     WS_GRAPHQL_URL: wss://api-graphql.bonde.devel/v1/graphql
  #   command:
  #   - pnpm
  #   - m
  #   - run
  #   - start
  #   - --filter
  #   - listener-mob-generator

  redes:
    image: nossas/bonde-redes:3.0.0
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1111}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-listeners-redes}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a1111}
      - GRAPHQL_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - HASURA_SECRET=${HASURA_SECRET:-a11111}
      - LAWYER_WIDGET_IDS=${LAWYER_WIDGET_IDS:-a1111}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.bonde.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-a1111}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - THERAPIST_WIDGET_IDS=${THERAPIST_WIDGET_IDS:-a1111}
      - WS_GRAPHQL_URL=${WS_GRAPHQL_URL:-ws://api-graphql.bonde.devel/v1/graphql}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER:-email@host}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS}
      - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - listener-redes

  redes-geolocation:
    image: nossas/bonde-redes:3.0.0
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1111}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-listeners-redes-geolocation}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a1111}
      - GRAPHQL_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - HASURA_SECRET=${HASURA_SECRET:-a11111}
      - LAWYER_WIDGET_IDS=${LAWYER_WIDGET_IDS:-a1111}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.bonde.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-a1111}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - THERAPIST_WIDGET_IDS=${THERAPIST_WIDGET_IDS:-a1111}
      - WS_GRAPHQL_URL=${WS_GRAPHQL_URL:-ws://api-graphql.bonde.devel/v1/graphql}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER:-email@host}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS}
      - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    command:
    - pnpm
    - m
    - run
    - start
    - --filter
    - listener-redes-geolocation

networks:
  default:
    name: bonde