version: '2'
services:

  cache:
    image: nossas/bonde-cache:v0.3.6
    # build: ../cache/
    environment:
      GIN_MODE: debug
      PORT: '3007'
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: Host:cache.bonde.devel
      traefik.enable: 'true'
      traefik.alias: redirect
      traefik.port: '3007'

  redirect:
    image: nossas/bonde-redirect:0.3.1
    # build: ../redirect/
    environment:
      GIN_MODE: debug
      PORT: '3007'
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: Host:redirect.bonde.devel
      traefik.enable: 'true'
      traefik.alias: redirect
      traefik.port: '3007'

  match-voluntarias:
    image: nossas/match-voluntarios:latest
    # build: ../match/
    environment:
      PORT: '5000'
      GOOGLE_APPLICATION_CREDENTIALS: /data/credentials.json
      GCLOUD_PROJECT: name-project
      REACT_APP_GOOGLE_CLIENT_KEY: key
    command:
    - npm
    - start
    labels:
      traefik.frontend.rule: Host:match-voluntarias.bonde.devel
      traefik.enable: 'true'
      traefik.alias: match-voluntarias
      traefik.port: '5000'
      traefik.acme: 'false'
      traefik.frontend.entryPoints: http

  docs-api-v1:
    image: nossas/bonde-docs:develop
    # build: ../docs-api-v1/
    command:
    - hugo
    - server
    - --bind=0.0.0.0
    labels:
      traefik.frontend.rule: Host:docs.bonde.devel
      traefik.port: '1313'
      traefik.enable: 'true'
      traefik.frontend.entryPoints: http

  notifications:
    image: nossas/bonde-notifications:develop
    # build: ../notifications/
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster:5432/bonde
      SMTP_ADDRESS: 'smtp'
      SMTP_PORT: '1025'
      SMTP_DOMAIN: 'bonde.devel'
      SMTP_USER_NAME: ''
      SMTP_PASSWORD: ''
      DEFAULT_FROM: 'email@bonde.devel'
      DB_CHANNEL: notifications_channel
      JWT_SECRET: 'segredo123'
      REDIS_URL: redis://redis:6379
      WORKERS: '5'

  maquinista:
    image: nossas/bonde-maquinista:develop
    environment:
      DATABASE_URL: postgres://monkey_user:monkey_pass@pgmaster:5432/bonde
      HUBOT_AUTH_ADMIN: admin
      HUBOT_GOOGLE_CSE_ID: O1
      HUBOT_GOOGLE_CSE_KEY: AI
      HUBOT_GOOGLE_SAFE_SEARCH: '''off'''
      HUBOT_NEWRELIC_ACCOUNT_ID: ca
      HUBOT_NEWRELIC_API_KEY: ''
      HUBOT_SENDGRID_KEY: SG
      HUBOT_SENDGRID_USER: apikey
      HUBOT_SLACK_TOKEN: x
      HUBOT_UPTIMEROBOT_APIKEY: u
      PORT: '8088'
      REDIS_URL: redis://redis:6379/hubot
      SECRET: 3a
    external_links:
    - common/redis3:redis
    labels:
      traefik.frontend.rule: Host:maquinista.bonde.org
      traefik.enable: 'true'
      traefik.alias: maquinista
      traefik.port: '8088'
      io.rancher.container.pull_image: always
      traefik.acme: 'false'
      traefik.frontend.entryPoints: http
