# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.2
COPY ./config/ /usr/share/kibana/config
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
