services:
  openapi:
    image: ${DOCKER_IMAGE:-nossas/open-api:latest}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:80}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    environment:
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-openapi.bonde.org,openapi.staging.bonde.org}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    labels:
      traefik.http.services.openapi.loadbalancer.server.port: '80'
      traefik.enable: 'true'
      traefik.http.routers.openapi.tls: true
      traefik.http.routers.openapi.tls.certresolver: myresolver
  
  depends_on:
    - etcd