services:
  accounts:
    image: nossas/bonde-clients:${DOCKER_IMAGE:-main}
    command: yarn pnpm m run start --filter accounts-client
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:3000}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      traefik.http.services.accounts.loadbalancer.server.port: '3000'
      traefik.enable: 'true'
  
  app:
    image: nossas/bonde-clients:${DOCKER_IMAGE:-main}
    command: yarn pnpm m run start --filter admin-client
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:5000}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      traefik.http.services.app.loadbalancer.server.port: '5000'
      traefik.enable: 'true'

  admin-canary:
    image: nossas/bonde-clients:${DOCKER_IMAGE:-main}
    command: yarn pnpm m run start --filter canary-client
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:3000}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      traefik.http.services.admin-canary.loadbalancer.server.port: '3000'
      traefik.enable: 'true'

  redes:
    image: nossas/bonde-clients:${DOCKER_IMAGE:-main}
    command: yarn pnpm m run start --filter redes-client
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:3000}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      traefik.http.services.redes.loadbalancer.server.port: '3000'
      traefik.enable: 'true'

  public:
    image: nossas/bonde-clients:${DOCKER_IMAGE:-main}
    command: yarn pnpm m run start --filter webpage-client
    environment:
      - PORT=3000
      - NODE_ENV=${PUBLIC_NODE_ENV:-development}
      - ACTION_SECRET_KEY=${PUBLIC_ACTION_SECRET_KEY}
      - REACT_APP_API_GRAPHQL_SECRET=${PUBLIC_HASURA_SECRET}
      - REACT_APP_PAGARME_KEY=${PUBLIC_PAGARME_KEY}
      - REACT_APP_DOMAIN_API_ACTIVISTS=${PUBLIC_HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      - REACT_APP_DOMAIN_API_GRAPHQL=${PUBLIC_HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      - REACT_APP_DOMAIN_API_REST=${PUBLIC_REST_API:-http://api-rest.bonde.devel}
      - REACT_APP_DOMAIN_PUBLIC=${DEFAULT_DOMAIN_RULE:-bonde.devel}
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:3000}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      traefik.http.services.public.loadbalancer.server.port: '3000'
      traefik.enable: 'true'