x-cli-zendesk: &cli-zendesk
  image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:feature-refactor-packages-2}
  environment:
    - COMMUNITY_ID=${COMMUNITY_ID:-1111}
    - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
    - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
    - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-cli-zendesk}
    - LAWYER_WIDGET_IDS=${LAWYER_WIDGET_IDS:-a1111}
    - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.bonde.devel/api}
    - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-a1111}
    - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
    - NODE_ENV=${NODE_ENV:-production}
    - WIDGET_IDS=${WIDGET_IDS:-a1111}
    - WS_GRAPHQL_URL=${WS_GRAPHQL_URL:-ws://api-graphql.bonde.devel/v1/graphql}
    - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
    - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
    - ZENDESK_API_USER=${ZENDESK_API_USER_WITH_TOKEN:-email@host}
    - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS}
    - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
    - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
    - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    - DEBUG=${DEBUG:-cli-zendesk*}
    - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-false}
    - HASURA_API_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
    - X_HASURA_ADMIN_SECRET=${X_HASURA_ADMIN_SECRET:-segredo123}
    # - WIDGET_IDS='{"ADVOGADA": 17633, "PSICÓLOGA": 17628, "MSR": 16850}'

services:

  cli-zendesk-ticket:
    <<: *cli-zendesk
    command:
    - pnpm
    - --filter
    - mda-cli-zendesk
    - run
    - start:ticket
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *

  cli-zendesk-user:
    <<: *cli-zendesk
    command:
    - pnpm
    - --filter
    - mda-cli-zendesk
    - run
    - start:user
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *

  start:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:feature-refactor-packages-2}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1111}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-listeners-solidarity}
      - GRAPHQL_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - HASURA_SECRET=${X_HASURA_ADMIN_SECRET:-a11111}
      - LAWYER_WIDGET_IDS=${LAWYER_WIDGET_IDS:-a1111}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.bonde.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-a1111}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - THERAPIST_WIDGET_IDS=${THERAPIST_WIDGET_IDS:-a1111}
      - WS_GRAPHQL_URL=${WS_GRAPHQL_URL:-ws://api-graphql.bonde.devel/v1/graphql}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER:-email@host}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS_EN}
      - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    command:
    - pnpm
    - --filter
    - mda-start
    - run
    - start

  match:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:feature-refactor-packages-2}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1111}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-a1111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111111.apm.us-east-1.aws.found.io}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-listeners-match}
      - GRAPHQL_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - HASURA_SECRET=${X_HASURA_ADMIN_SECRET:-a11111}
      - LAWYER_WIDGET_IDS=${LAWYER_WIDGET_IDS:-a1111}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.bonde.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-a1111}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - THERAPIST_WIDGET_IDS=${THERAPIST_WIDGET_IDS:-a1111}
      - WS_GRAPHQL_URL=${WS_GRAPHQL_URL:-ws://api-graphql.bonde.devel/v1/graphql}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-a1111}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaa.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER:-email@host}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS_EN}
      - BRASIL_API_KEY=${BRASIL_API_KEY:-a11111}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-a11111}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY-a11111}
    command:
    - pnpm
    - --filter
    - mda-match
    - run
    - start

  zendesk-events:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:feature-refactor-packages-2}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1}
      - DEBUG=${DEBUG:-mda-zendesk-events*}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-aaaa1}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://aaaa1.apm.us-east-1.aws.found.io}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-aaaa1}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-aaaa1}
      - HASURA_API_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.nossas.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-aaaa1}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=80
      - X_HASURA_ADMIN_SECRET=${X_HASURA_ADMIN_SECRET:-aaaa1}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-aaaa1}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaaa1.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER_WITH_TOKEN:-email@host/token}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS_SOLIDARITY_COUNT}
      - WIDGET_IDS=${WIDGET_IDS_SOLIDARITY_COUNT:-aaaa1}
    command:
      - pnpm
      - --filter
      - mda-zendesk-events
      - run
      - start
    labels:
      - traefik.http.services.zendesk-events.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.zendesk-events.tls=true
      - traefik.http.routers.zendesk-events.tls.certresolver=myresolver

  mautic-events:
    image: ${DOCKER_IMAGE:-nossas/mapa-do-acolhimento:feature-refactor-packages-2}
    environment:
      - COMMUNITY_ID=${COMMUNITY_ID:-1}
      - DEBUG=${DEBUG:-mda-mauitic-events*}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-aaaa1}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://aaaa1.apm.us-east-1.aws.found.io}
      - GEOCODING_API_KEY=${GEOCODING_API_KEY:-aaaa1}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-aaaa1}
      - HASURA_API_URL=${GRAPHQL_URL:-http://api-graphql.bonde.devel/v1/graphql}
      - MAUTIC_API_URL=${MAUTIC_API_URL:-http://mautic.nossas.devel/api}
      - MAUTIC_PASSWORD=${MAUTIC_PASSWORD:-aaaa1}
      - MAUTIC_USERNAME=${MAUTIC_USERNAME:-email@host}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=80
      - X_HASURA_ADMIN_SECRET=${X_HASURA_ADMIN_SECRET:-aaaa1}
      - ZENDESK_API_TOKEN=${ZENDESK_API_TOKEN:-aaaa1}
      - ZENDESK_API_URL=${ZENDESK_API_URL:-https://aaaa1.zendesk.com/api/v2/}
      - ZENDESK_API_USER=${ZENDESK_API_USER_WITH_TOKEN:-email@host/token}
      - ZENDESK_ORGANIZATIONS=${ZENDESK_ORGANIZATIONS}
      - WIDGET_IDS=${WIDGET_IDS_:-aaaa1}
    command:
      - pnpm 
      - --filter 
      - mda-mautic-events 
      - run
      - start
    labels:
      - traefik.http.services.mautic-events.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.mautic-events.tls=true
      - traefik.http.routers.mautic-events.tls.certresolver=myresolver
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

networks:
  default:
    name: bonde
