version: '2'
services:
  metabase:
    image: metabase/metabase:v0.49.23.2
    environment:
      JAVA_TIMEZONE: America/Sao_Paulo
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DB_DBNAME} 
      MB_DB_PORT: ${MB_DB_PORT:-5432}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
      JAVA_TOOL_OPTIONS: -Xmx2g

    ports:
    - 3000/tcp

    labels:
      - traefik.enable=true
      - traefik.http.services.metabase.loadbalancer.server.port=3000
      - traefik.http.routers.metabase.tls=true
      - traefik.http.routers.metabase.tls.certresolver=myresolver
networks:
  default:
    external:
      name: bonde      
