services:
  mautic:
    image: mautic/mautic:latest
    environment:
      - MAUTIC_DB_HOST=${MAUTIC_DB_HOST:-mauticdb}
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME:-mautic}
      - MAUTIC_DB_PASSWORD=${MAUTIC_DB_PASSWORD:-mysecret}
      - MAUTIC_DB_USER=${MAUTIC_DB_USER:-root}
      - MAUTIC_RUN_CRON_JOBS=${MAUTIC_RUN_CRON_JOBS:-true}
      - MYSQL_PORT_3306_TCP=${MYSQL_PORT_3306_TCP:-3306}
      - MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
    depends_on:
      - mauticdb
    volumes:
    - mautic_data:/var/www/html
    # ports:
    # - 3000:80/tcp
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      - traefik.http.services.mautic.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.mautic.tls=true
      - traefik.http.routers.mautic.tls.certresolver=myresolver
  mauticdb:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysecret}
    volumes:
    - mysql_data:/var/lib/mysql
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_general_ci

volumes:
  mautic_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    external:
      name: bonde