x-api-rest: &api-rest
  image: nossas/bonde-server:0.10.9
  environment:
    - DATABASE_URL=${DATABASE_URL:-postgres://user:password@postgres:5432/bonde}
    - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-111111}
    - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111.apm.us-east-1.aws.cloud.es.io:443}
    - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-workers-rest-mailchimp}
    - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-true}
    - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    - AWS_ID=${AWS_ID:-a111111}
    - AWS_SECRET=${AWS_SECRET:-a11111}
    - PORT=${PORT:-3000}
    - RAILS_ENV=${RAILS_ENV:-production}
    - SMTP_HOST=${SMTP_HOST:-smtp}
    - SMTP_PASSWORD=${SMTP_PASSWORD:-a1}
    - SMTP_PORT=${SMTP_PORT:-587}
    - SMTP_USERNAME=${SMTP_USERNAME:-apikey}
    - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY:-111-us6}
    - MAILCHIMP_GROUP_ID=${MAILCHIMP_GROUP_ID:-22}
    - MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID:-c123213}
    - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
    - WEB_MEMORY=${WEB_MEMORY:-256}
    - ORG_RECIPIENT_ID=${ORG_RECIPIENT_ID:-a1111}
    - PAGARME_API_KEY=${PAGARME_API_KEY:-a1111}
    - JWT_SECRET=${JWT_SECRET:-segredo123}
    - LOG_LEVEL=${LOG_LEVEL:-info}

x-payments: &payments
  image: nossas/bonde-payments:develop
  environment:
    - PAGARME_API_KEY=${PAGARME_API_KEY:-a111}
    - DATABASE_URL=${DATABASE_URL:-postgres://user:pass@postgres:5432/bonde}
    - RUBY_ENV=${RUBY_ENV:-production}
    - NODE_ENV=${NODE_ENV:-production}
    - RAILS_ENV=${RAILS_ENV:-production}
    - AMOUNT=${AMOUNT:-100}

services:

  donations-recovery-from-metadata:
    <<: *api-rest
    command:
    - bundle
    - exec
    - rake
    - payments:recovery_from_metadata
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *

  payments-transferred:
    <<: *payments
    command:
    - ruby
    - -I
    - .
    - -r
    - app/main
    - -e
    - Main.new.sync_recipients 'transferred'
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *
  donations:
    <<: *api-rest
    command:
    - bundle
    - exec
    - rake
    - payments:sync_donations
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *

  payments:
    <<: *payments
    command:
    - ruby
    - -I
    - .
    - -r
    - app/main
    - -e
    - Main.new.sync_recipients 'available'
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *
  donations-schedule-charges:
    <<: *api-rest
    command:
    - bundle
    - exec
    - rake
    - subscriptions:schedule_charges
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *
  donations-sync-gateway-transactions:
    <<: *api-rest
    command:
    - bundle
    - exec
    - rake
    - payments:sync_gateway_transactions
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *

  payments-waiting-funds:
    <<: *payments
    command:
    - ruby
    - -I
    - .
    - -r
    - app/main
    - -e
    - Main.new.sync_recipients 'waiting_funds'
    labels:
      cron.restart_timeout: '86400'
      cron.schedule: 0 0 0 * * *

  # https://github.com/rancher/container-crontab
  container-crontab:
    image: rancher/container-crontab:v0.5.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  donations-notifications:
    image: nossas/bonde-notifications:develop
    # build: ../notification-service/
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://user:pass@postgres:5432/bonde}
      - SMTP_DOMAIN=${SMTP_HOST:-smtp}
      - SMTP_ADDRESS=${SMTP_HOST:-smtp}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-SG.fdsafdsafdsafdsa}
      - SMTP_PORT=${SMTP_PORT:-'587'}
      - SMTP_USER_NAME=${SMTP_USERNAME:-apikey}
      - DEFAULT_FROM=${DEFAULT_NOTIFICATION_FROM:-contato@bonde.devel}
      - DB_CHANNEL=notifications_channel
      - JWT_SECRET=${JWT_SECRET:-segredo123}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - WORKERS=1
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
      - WEB_MEMORY=${WEB_MEMORY:-256}

networks:
  default:
    name: bonde