services:
  # api-rest:
  #   image: nossas/bonde-server:0.10.9
  #   environment:
  #     - API_HOST=${API_HOST:-api-rest.bonde.devel}
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AAAAA}
  #     - AWS_BUCKET=${AWS_BUCKET:-hub-central}
  #     - AWS_ENDPOINT=${AWS_ENDPOINT:-https://s3.amazonaws.com}
  #     - AWS_ID=${AWS_ID:-AAAAAA}
  #     - AWS_ROUTE53_REGION=${AWS_ROUTE53_REGION:-sa-east-1}
  #     - AWS_ROUTE53_SYNC=${AWS_ROUTE53_SYNC:-force}
  #     - AWS_ROUTE_IP=${AWS_ROUTE_IP:-127.0.0.1}
  #     - AWS_SECRET=${AWS_SECRET:-LLLLLLLLL}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-LLLLLLLLL}
  #     - CLIENT_APP_NAME=${CLIENT_APP_NAME:-client-app}
  #     - CLIENT_HOST=${CLIENT_HOST:-bonde.devel}
  #     - DATABASE_URL=${DATABASE_URL:-postgres://user:pass@postgres:5432/bonde}
  #     - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-'true'}
  #     - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-Bonde API Rest}
  #     - JWT_SECRET=${JWT_SECRET:-segredo123}
  #     - JWT_TYPE=${JWT_TYPE:-postgraphql.jwt_token}
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #     - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY:-aaaaa-us6}
  #     - MAILCHIMP_GROUP_ID=${MAILCHIMP_GROUP_ID:-'111'}
  #     - MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID:-c111111}
  #     - ORG_RECIPIENT_ID=${ORG_RECIPIENT_ID:-re_fdsafdsafdsa}
  #     - PAGARME_API_KEY=${PAGARME_API_KEY:-ak_test_fdsafdsafdsa}
  #     - PORT=${PORT:-'3000'}
  #     - RAILS_ENV=${RAILS_ENV:-production}
  #     - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES:-enabled}
  #     - REDIS_URL=${REDIS_URL:-redis://redis:6379}
  #     - SECRET_KEY_BASE=${SECRET_KEY_BASE:-seeeeeeeeeee}
  #     - SENDGRID_PASSWORD=${SENDGRID_PASSWORD:-SG.fdsafdsa.fdsafdsafdsa}
  #     - SENDGRID_USERNAME=${SENDGRID_USERNAME:-apikey}
  #     - SMTP_HOST=${SMTP_HOST:-smtp}
  #     - SMTP_PASSWORD=${SMTP_PASSWORD:-SG.fdsafdsafdsafdsa}
  #     - SMTP_PORT=${SMTP_PORT:-'587'}
  #     - SMTP_USERNAME=${SMTP_USERNAME:-apikey}
  #     - WEB_CONCURRENCY=${WEB_CONCURRENCY:-'1'}
  #     - WEB_MEMORY=${WEB_MEMORY:-'256'}
  #     - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-fdsafdsafdsa}
  #     - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://fdsafdsafdsafdsa.apm.us-east-1.aws.found.io}
  #   command:
  #     - bundle exec puma -C config/puma.rb
  #   labels:
  #     - traefik.http.services.api-rest.loadbalancer.server.port=3000
  #     - traefik.enable=true
  #     - traefik.http.routers.api-rest.tls=true
  #     - traefik.http.routers.api-rest.tls.certresolver=myresolver

  api-graphql:
    image: hasura/graphql-engine:v2.2.0
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=${HASURA_GRAPHQL_DATABASE_URL:-postgres://user:pass@postgres:5432/bonde}
      - HASURA_GRAPHQL_ENABLE_CONSOLE=${HASURA_GRAPHQL_ENABLE_CONSOLE:-'false'}
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET:-segredo123}
      - WEBHOOK_MAIL_URL=${WEBHOOK_MAIL_URL:-https://webhook-mail.bonde.devel/webhook}
      - WEBHOOK_ACTIVISTS_PRESSURE_URL=${WEBHOOK_ACTIVISTS_PRESSURE_URL:-https://webhook-activists.bonde.devel/webhook/pressure}
      - SCHEMA_API_V2_URL=${SCHEMA_API_V2_URL:-https://api-v2.bonde.devel/graphql}
      - SCHEMA_API_AUTH_URL=${SCHEMA_API_AUTH_URL:-https://api-accounts.bonde.devel/graphql}
      - WEBHOOK_INVITATIONS_URL=${WEBHOOK_INVITATIONS_URL:-https://webhook-accounts.bonde.devel/invitations}
      - SCHEMA_API_ACTIVISTS_URL=${SCHEMA_API_ACTIVISTS_URL:-https://activists.bonde.devel/graphql}
      - SCHEMA_API_NOTIFICATIONS_URL=${SCHEMA_API_NOTIFICATIONS_URL:-https://notifications.bonde.devel/graphql}
      - SCHEMA_API_DOMAINS_URL=${SCHEMA_API_DOMAINS_URL:-https://api-domains.bonde.devel/graphql}
      - SCHEMA_API_PAYMENTS_URL=${SCHEMA_API_PAYMENTS_URL:-https://api-payments.bonde.devel/graphql}
      - SCHEMA_API_REDES_URL=${SCHEMA_API_REDES_URL:-https://api-redes.bonde.devel/graphql}
      - HASURA_GRAPHQL_JWT_SECRET=${HASURA_GRAPHQL_JWT_SECRET}
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=${HASURA_GRAPHQL_UNAUTHORIZED_ROLE:-anonymous}
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=${HASURA_GRAPHQL_ENABLED_LOG_TYPES:-startup, query-log, http-log, webhook-log, websocket-log}
      - ACTION_BASE_URL=${ACTION_BASE_URL:-https://mailchimp-resync.bonde.devel}
      - WEBHOOK_PLIP_MAUTIC_URL=${WEBHOOK_PLIP_MAUTIC_URL:-https://n8n.bonde.devel/webhook/plip-mautic}
    labels:
      - traefik.http.services.api-graphql.loadbalancer.server.port=8080
      - traefik.enable=true
      - traefik.http.routers.api-graphql.tls=true
      - traefik.http.routers.api-graphql.tls.certresolver=myresolver