# Settings and configurations that are common for all containers
# https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml
x-minio-common:
  &minio-common
  image: quay.io/minio/minio:RELEASE.2022-05-23T18-45-11Z
  command: server --address ":9000" --console-address ":9001" /minio/data1

  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
  healthcheck:
    test:
      [
        "CMD",
        "curl",
        "-f",
        "http://localhost:9000/minio/health/live"
      ]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio:
    <<: *minio-common
    hostname: minio
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    labels:
      traefik.http.services.minio.loadbalancer.server.port: '9000'
      traefik.enable: 'true'
      traefik.http.routers.minio.tls: true
      traefik.http.routers.minio.tls.certresolver: myresolver

  api-payments:
    image: ${DOCKER_IMAGE:-nossas/bonde-apis:v1.2.6}
    environment:
      GRAPHQL_HTTP_URL: ${HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      HASURA_SECRET: ${HASURA_SECRET}
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET:-segredo123}
      PAGARME_API_KEY: ${PAGARME_KEY}
      PORT: '3000'
    command:
      - pnpm
      - --filter
      - payments-api
      - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      traefik.http.services.api-payments.loadbalancer.server.port: '3000'
      traefik.enable: 'true'
      traefik.http.routers.api-payments.tls: true
      traefik.http.routers.api-payments.tls.certresolver: myresolver
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:3000}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

  api-domains:
    image: ${DOCKER_IMAGE:-nossas/bonde-apis:v1.2.6}
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_ROUTE53_REGION: ${AWS_ROUTE53_REGION}
      AWS_ROUTE_IP: ${AWS_ROUTE_IP}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      HASURA_SECRET: ${HASURA_SECRET}
      GRAPHQL_HTTP_URL: ${HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      ETCD_URL: ${ETCD_URL:-http://etcd:2379}
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET:-segredo123}
      PORT: '3000'
    command:
      - pnpm
      - --filter
      - domains-api
      - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      traefik.http.services.api-domains.loadbalancer.server.port: '3000'
      traefik.enable: 'true'
      traefik.http.routers.api-domains.tls: true
      traefik.http.routers.api-domains.tls.certresolver: myresolver
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:3000}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

  api-activists:
    image: ${DOCKER_IMAGE:-nossas/bonde-apis:v1.2.6}
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      ACTION_SECRET_KEY: ${ACTION_SECRET_KEY}
      GRAPHQL_HTTP_URL: ${HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      HASURA_SECRET: ${HASURA_SECRET}
      HOST: 0.0.0.0
      PORT: '3000'
    command:
      - pnpm
      - --filter
      - activists-api
      - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      traefik.http.services.api-activists.loadbalancer.server.port: '3000'
      traefik.enable: 'true'
      traefik.http.routers.api-activists.tls: true
      traefik.http.routers.api-activists.tls.certresolver: myresolver
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:3000}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

  api-redes:
    image: ${DOCKER_IMAGE:-nossas/bonde-apis:v1.2.6}
    environment:
      GRAPHQL_HTTP_URL: ${HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      HASURA_SECRET: ${HASURA_SECRET}
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET:-segredo123}
      PORT: '3000'
      ZENDESK_API_TOKEN: ${ZENDESK_API_TOKEN}
      ZENDESK_API_URL: ${ZENDESK_API_URL}
      ZENDESK_API_USER: ${ZENDESK_API_USER}
      ZENDESK_ORGANIZATIONS: ${ZENDESK_ORGANIZATIONS}
    command:
      - pnpm
      - --filter
      - redes-api
      - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      traefik.http.services.api-redes.loadbalancer.server.port: '3000'
      traefik.enable: 'true'
      traefik.http.routers.api-redes.tls: true
      traefik.http.routers.api-redes.tls.certresolver: myresolver
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:3000}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

  api-accounts:
    image: ${DOCKER_IMAGE:-nossas/bonde-apis:v1.2.6}
    environment:
      ACCOUNTS_REGISTER_URL: https://accounts.${DEFAULT_DOMAIN_RULE}/register
      GRAPHQL_HTTP_URL: ${HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      APP_DOMAIN: ${DEFAULT_DOMAIN_RULE}
      HASURA_SECRET: ${HASURA_SECRET}
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET:-segredo123}
      LOG_LEVEL: debug
      PORT: '4001'
    command:
      - pnpm
      - --filter
      - accounts-api
      - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      traefik.http.services.api-accounts.loadbalancer.server.port: '4001'
      traefik.enable: 'true'
      traefik.http.routers.api-accounts.tls: true
      traefik.http.routers.api-accounts.tls.certresolver: myresolver
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:4001}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

  api-accounts-local:
    image: ${DOCKER_IMAGE:-nossas/bonde-apis:v1.2.6}
    environment:
      ACCOUNTS_REGISTER_URL: https://accounts.${DEFAULT_DOMAIN_RULE}/register
      GRAPHQL_HTTP_URL: ${HASURA_API:-http://api-graphql.bonde.devel/v1/graphql}
      HASURA_SECRET: ${HASURA_SECRET}
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET:-segredo123}
      LOG_LEVEL: debug
      PORT: '4001'
      NODE_ENV: 'development'
      APP_DOMAIN: '.bonde.devel'
    command:
      - pnpm
      - --filter
      - accounts-api
      - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      traefik.http.services.api-accounts-local.loadbalancer.server.port: '4001'
      traefik.enable: 'true'
      traefik.http.routers.api-accounts-local.tls: true
      traefik.http.routers.api-accounts-local.tls.certresolver: myresolver
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:4001}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

  api-notifications:
    image: ${DOCKER_IMAGE:-nossas/bonde-apis:v1.2.6}
    environment:
      ELASTICSEARCH_CLOUD_ID: ${ELASTICSEARCH_CLOUD_ID}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTIC_APM_SECRET_TOKEN: ${ELASTIC_APM_SECRET_TOKEN}
      ELASTIC_APM_SERVER_URL: ${ELASTIC_APM_SERVER_URL}
      ELASTIC_APM_SERVICE_NAME: ${ELASTIC_APM_SERVICE_NAME:-notifications}
      HOST: 0.0.0.0
      PORT: '3000'
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_WEBHOOK_KEY: ${SENDGRID_WEBHOOK_KEY}
    command:
      - pnpm
      - --filter
      - notifications
      - start
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      traefik.http.services.api-notifications.loadbalancer.server.port: '3000'
      traefik.enable: 'true'
      traefik.http.routers.api-notifications.tls: true
      traefik.http.routers.api-notifications.tls.certresolver: myresolver
    # healthcheck:
    #   test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:3000}"
    #   interval: "60s"
    #   timeout: "3s"
    #   start_period: "5s"
    #   retries: 3

volumes:
  data1-1:
  data1-2:


networks:
  default:
    name: bonde
