services:
  adp-redirect:
    image: nossas/bonde-redirect:0.4.7
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.adp-redirect.priority=1
      - traefik.http.services.adp-redirect.loadbalancer.server.port=3007
      - traefik.http.routers.adp-redirect.tls=true
      - traefik.http.routers.adp-redirect.tls.certresolver=myresolver
      - traefik.http.routers.adp-redirect.rule=${ADP_REDIRECT_RUL}



      