services:

  phone:
    image: nossas/bonde-phone:1.1.0
    environment:
      - AMOUNT=${AMOUNT:-100}
      - APP_DOMAIN=${PHONE_APP_DOMAIN:-http://phone.bonde.devel}
      - DATABASE_URL=${DATABASE_URL:-postgres://user:pass@postgres:5432/bonde}
      - DEBUG=${DEBUG:-1}
      - ENABLE_TWILIO_CALL=${ENABLE_TWILIO_CALL:-1}
      - PORT=5000
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-aaa1}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-aaa1}
      - TWILIO_NUMBER=${TWILIO_NUMBER:-'+551111111111'}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
      - WEB_MEMORY=${WEB_MEMORY:-256}
    command:
      - yarn
      - run
      - dev
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - traefik.http.services.phone.loadbalancer.server.port=5000
      - traefik.enable=true
      - traefik.http.routers.phone.tls=true
      - traefik.http.routers.phone.tls.certresolver=myresolver
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:5000/ping}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  beta:
    image: nossas/bonde-bot-beta:3.1.8
    environment:
      - API_URL=${API_URL:-http://api-v1.bonde.devel}
      - APP_DOMAIN=${BETA_APP_DOMAIN:-http://beta.bonde.devel}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-aaaa1}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://aaaaa1.apm.us-east-1.aws.cloud.es.io:443}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-Bonde Bot Beta}
      - FORM_MOBILIZATION_ID=${FORM_MOBILIZATION_ID:-'1305'}
      - FORM_WIDGET_ID=${FORM_WIDGET_ID:-'23416'}
      - GRAPHQL_URL=${GRAPHQL_URL:-http://api-v2.bonde.devel/graphql}
      - JWT_TOKEN=${JWT_TOKEN:-aaaa1}
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-5000}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SPEECH_VERSION=${SPEECH_VERSION:-v2}
      - WIT_SERVER_ACCESS_TOKEN=${WIT_SERVER_ACCESS_TOKEN:-aaaa1}
      - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-false}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - traefik.http.services.beta.loadbalancer.server.port=5000
      - traefik.enable=true
      - traefik.http.routers.beta.tls=true
      - traefik.http.routers.beta.tls.certresolver=myresolver
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:5000}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  redirect:
    image: nossas/bonde-redirect:main
    environment:
      - GIN_MODE=${GIN_MODE:-debug}
      - PORT=${PORT:-3007}
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - traefik.http.services.redirect.loadbalancer.server.port=3007
      - traefik.enable=true
      - traefik.http.routers.redirect.tls=true
      - traefik.http.routers.redirect.tls.certresolver=myresolver
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:3007}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

networks:
  default:
    name: bonde
