version: '3'

services:
  botpress:
    image: botpress/server
    command: /botpress/bp
    expose:
      - 3000
    environment:
      - DATABASE_URL=postgres://postgres:secretpw@postgres:5435/botpress_db
      - REDIS_URL=redis://redis:6379?password=redisPassword
      - BP_MODULE_NLU_DUCKLINGURL=http://botpress_lang:8000
      - BP_MODULE_NLU_LANGUAGESOURCES=[{"endpoint":"http://botpress_lang:3100"}]
      - CLUSTER_ENABLED=true
      - BP_PRODUCTION=true
      - BPFS_STORAGE=database
    depends_on:
      - botpress_lang
      - postgres
      - redis
    volumes:
      - botpress-data:/botpress/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-wget -qO- localhost:3000}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    labels:
      traefik.http.services.botpress.loadbalancer.server.port: "3000"
      traefik.enable: "true"
      traefik.http.routers.botpress.tls: true
      traefik.http.routers.botpress.tls.certresolver: myresolver

  botpress_lang:
    image: botpress/server
    command: bash -c "./duckling -p 8000 & ./bp lang --langDir /botpress/lang --port 3100"
    expose:
      - 3100
      - 8000
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    pull_policy: always
    volumes:
      - botpress-lang:/botpress/lang

  postgres:
    image: postgres:11.2-alpine
    expose:
      - 5435
    environment:
      PGPORT: 5435
      POSTGRES_DB: botpress_db
      POSTGRES_PASSWORD: secretpw
      POSTGRES_USER: postgres
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5.0.5-alpine
    expose:
      - 6379
    command: redis-server --requirepass redisPassword
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      - redisdata:/data

  alpine:
    image: alpine
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - botpress-data:/botpress/data

volumes:
  pgdata:
  redisdata:
  botpress-data:
  botpress-lang:

networks:
  default:
    name: bonde
