services:

  mailchimp:
    image: nossas/bonde-server:0.10.9
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://user:password@postgres:5432/bonde}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-111111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111.apm.us-east-1.aws.cloud.es.io:443}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-workers-rest-mailchimp}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - AWS_ID=${AWS_ID:-a111111}
      - AWS_SECRET=${AWS_SECRET:-a11111}
      - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-'false'}
      - PORT=${PORT:-3000}
      - RAILS_ENV=${RAILS_ENV:-production}
      - SMTP_HOST=${SMTP_HOST:-smtp}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-a1}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-apikey}
      - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY:-111-us6}
      - MAILCHIMP_GROUP_ID=${MAILCHIMP_GROUP_ID:-22}
      - MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID:-c123213}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
      - WEB_MEMORY=${WEB_MEMORY:-256}
    command:
    - bundle
    - exec
    - sidekiq
    - -c
    - '5'
    - -q
    - mailchimp_synchro
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  mailers:
    image: nossas/bonde-server:0.10.9
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://user:password@postgres:5432/bonde}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-111111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111.apm.us-east-1.aws.cloud.es.io:443}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-workers-rest-mailers}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - AWS_ID=${AWS_ID:-a111111}
      - AWS_SECRET=${AWS_SECRET:-a11111}
      - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-'false'}
      - PORT=${PORT:-3000}
      - RAILS_ENV=${RAILS_ENV:-production}
      - SMTP_HOST=${SMTP_HOST:-smtp}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-a1}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-apikey}
      - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY:-111-us6}
      - MAILCHIMP_GROUP_ID=${MAILCHIMP_GROUP_ID:-22}
      - MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID:-c123213}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
      - WEB_MEMORY=${WEB_MEMORY:-256}
    cpuset: '1'
    cpu_shares: 512
    command:
    - bundle
    - exec
    - sidekiq
    - -q
    - default
    - -q
    - mailers
    - -c
    - '5'
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  mailchimp-resync:
    image: nossas/bonde-workers:0.0.6
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://user:password@postgres:5432/bonde}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN:-111111}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-https://1111.apm.us-east-1.aws.cloud.es.io:443}
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-workers-mailchimp-resync}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - AWS_ID=${AWS_ID:-a111111}
      - AWS_SECRET=${AWS_SECRET:-a11111}
      - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE:-'false'}
      - PORT=${PORT:-3000}
      - RAILS_ENV=${RAILS_ENV:-production}
      - SMTP_HOST=${SMTP_HOST:-smtp}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-a1}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-apikey}
      - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY:-111-us6}
      - MAILCHIMP_GROUP_ID=${MAILCHIMP_GROUP_ID:-22}
      - MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID:-c123213}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-1}
      - WEB_MEMORY=${WEB_MEMORY:-256}
      - NODE_ENV=${NODE_ENV:-production}
    command:
    - pnpm
    - m
    - run
    - worker
    - --filter
    - resync-mailchimp
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

networks:
  default:
    name: bonde